### PR TITLE
fix_err_OCP-22606

### PR DESCRIPTION
**Pull request by geliu2016**
@liangxia Just fix a update for this autoscript, pls help to reivew it. thanks

### CODE REVIEW

**Comment by liangxia** [comment]
Removing checkpoint need feature team to review.

**Comment by geliu2016** [comment]
@xingxingxia pls help to review this pr, the backgroud is result from: https://bugzilla.redhat.com/show_bug.cgi?id=1686776, thanks

**Comment by xingxingxia** [comment]
Ge, [1686776#c7](https://bugzilla.redhat.com/show_bug.cgi?id=1686776#c7) says move to new etcd-ha-operator, what does this mean? Is your case still needed? Or is the case needed to be replaced with etcd-ha-operator case?

**Comment by geliu2016** [comment]
@xingxingxia I have not idea for etcd-ha-operator, this case is check the etcd operator is working well in upgrade, and it also fit for 4.5/4.5 now, I still keep it.

**Comment by xingxingxia** [comment]
Ge, I suggest:
1 confirm with Dev what that means.
2 confirm if we ship olm-managed etcd-operator or etcd-ha-operator.

**Comment by xingxingxia** [comment]
As to the PR, lgtm if you are sure to remove the lines. Just after removing it, what will be the purpose of creating etcd-cluster.yaml in upgrade-prepare?

**Comment by geliu2016** [comment]
@xingxingxia Just add more resource to ensure etcd-opreator status is works well, no negative effect to test.

**Comment by xingxingxia** [comment]
No more comment from my side.

**Comment by geliu2016** [comment]
@liangxia pls help to review, thanks

**Pull request merged**
