### PR TITLE
Adding  RDU IPI Bare Metal IaaS

### PR DESCRIPTION
**Pull request by jadhaj**

### CODE REVIEW

**Review by pruan-rht — COMMENTED** [review]
/lgtm
/approve
@jadhaj might want to add what RDU stands for.

**Comment by jadhaj** [comment]
@pruan-rht We got Dell servers to use for deploying IPI on BM on Redhat USA labs (RDU)

**Comment by jadhaj** [comment]
Related to MR https://gitlab.cee.redhat.com/aosqe/cucushift-internal/-/merge_requests/31

**Pull request merged**
