### PR TITLE
OCPQE-16741: OVN: fix leader step to use the correct clipboard

### PR DESCRIPTION
**Pull request by rbbratta**
Also fix else/end indent after elseif

### CODE REVIEW

**Comment by rbbratta** [comment]
/retitle OCPQE-16741: OVN: fix leader step to use the correct clipboard

**Comment by rbbratta** [comment]
@openshift/team-sdn-qe PTAL

**Comment by rbbratta** [comment]
https://file.rdu.redhat.com/~rbrattai/logs/ocpqe-16741.log

```

[17:29:53] INFO> nil node_name var value means we don't care about resource specific db pod hence choosing a random ovnkube-node

[17:29:54] INFO> cb.new_north_leader.name = ovnkube-node-sgb9g

[17:29:54] INFO> cb.new_north_leader.node_name = rbrattai-o15g44-v4tgs-master-0.c.openshift-qe.internal


[17:30:33] INFO> Exit Status: 0
waiting for operation up to 3600 seconds..

[17:30:34] INFO> nil node_name var value means we don't care about resource specific db pod hence choosing a random ovnkube-node
waiting for operation up to 3600 seconds..

[17:30:35] INFO> cb.south_leader.name = ovnkube-node-lg6vr

[17:30:35] INFO> cb.south_leader.node_name = rbrattai-o15g44-v4tgs-worker-c-p67ch.c.openshift-qe.internal

```

**Comment by rbbratta** [comment]
```
waiting for operation up to 3600 seconds..

[17:30:57] INFO> nil node_name var value means we don't care about resource specific db pod hence choosing a random ovnkube-node

[17:30:58] INFO> cb.new_south_leader.name = ovnkube-node-zk9sv

[17:30:58] INFO> cb.new_south_leader.node_name = rbrattai-o15g44-v4tgs-master-2.c.openshift-qe.internal


```

The clipboard used are `new_north_leader` and `new_south_leader`.

**Comment by zhaozhanqi** [comment]
@rbbratta thanks for the update
/lgtm
/approve

**Pull request merged**
