### PR TITLE
Created clusterautoscaler resource

### PR DESCRIPTION
**Pull request by miyadav**
@jhou1 @sunzhaohua2 @huali9 PTAL , the test ws unstable as 3 machines were not always needed on different platforms , I have modified it to make sure more than one is present after scaling , CI issue raised was - https://issues.redhat.com/browse/OCPQE-8285
`
            instanceId: i-053ac240688f3d0c8
            instanceState: running
      kind: List
      metadata:
        resourceVersion: ""
        selfLink: ""
      [06:39:22] INFO> Exit Status: 0
      [06:39:22] INFO> Shell Commands: oc delete machines machineset-clone-30783-6hwjp --wait=false --kubeconfig=/home/miyadav/workdir/miyadav-miyadavx/ocp4_admin.kubeconfig --namespace=openshift-machine-api
      machine.machine.openshift.io "machineset-clone-30783-6hwjp" deleted
      [06:39:24] INFO> Exit Status: 0
      [06:39:25] INFO> oc get machines machineset-clone-30783-6hwjp --output=yaml --kubeconfig=/home/miyadav/workdir/miyadav-miyadavx/ocp4_admin.kubeconfig --namespace=openshift-machine-api
      [06:40:06] INFO> After 18 iterations and 42 seconds:
      
      STDERR:
      Error from server (NotFound): machines.machine.openshift.io "machineset-clone-30783-6hwjp" not found
      [06:40:06] INFO> Shell Commands: oc get machines machineset-clone-30783-6hwjp --output=yaml --kubeconfig=/home/miyadav/workdir/miyadav-miyadavx/ocp4_admin.kubeconfig --namespace=openshift-machine-api
      
      STDERR:
      Error from server (NotFound): machines.machine.openshift.io "machineset-clone-30783-6hwjp" not found
      [06:40:08] INFO> Exit Status: 1
      [06:40:08] INFO> Shell Commands: rm -r -f -- /home/miyadav/workdir/miyadav-miyadavx
      
      [06:40:09] INFO> Exit Status: 0
      [06:40:10] INFO> === End After Scenario: Cluster should automatically scale up and scale down with clusterautoscaler deployed ===
1 scenario (1 passed)
19 steps (19 passed)
4m11.067s
[06:40:10] INFO> === At Exit ===
`

### CODE REVIEW

**Comment by jhou1** [comment]
I think we intentionally scaled it to 3 for the autoscaler test. If the machineSet did not scale to 3, we have to consider increasing the workloads in order for it to scale.

Setting `>= 1` will make the test always pass and miss its real checkpoint. When we created the machineSet and the machine becomes running, you already have the machineset's replica `>= 1`. So even if the autoscaler scenario is not run, that step `Then the expression should be true> machine_set.desired_replicas(cached: false) >= 1` will yield true and pass.

**Comment by miyadav** [comment]
After analysis it found clusterautoscaler was not getting created , looking if such is possible in other cases as well , where we scale cluster.
@jhou1 @sunzhaohua2 @huali9  PTAL..if you feel anything else needs to be looked at as well .. 
In the issue that ci_watcher raised I could not find` "clusterautoscaler.autoscaling.openshift.io/default created"` in logs ..
Working well now - https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/287553/console

**Comment by jhou1** [comment]
I took a look of the `upgrade-prepare` scenario, we'd expect the cluster autoscaler be created during prepare stage

**Comment by miyadav** [comment]
thanks @jhou1  @sunzhaohua2 will revisit ..

**Comment by miyadav** [comment]
This is not required , mistakenly opened .

**Pull request closed without merging**
