### PR TITLE
   fix the test on disconnected profiles

### PR DESCRIPTION
**Pull request by sandeepknd**
Hi @geliu2016 ,
Its working fine on both connected and disconnected platforms with proxy and without proxy.
Please find the below logs.
[connected profile no proxy](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4193/console)
[disconnected with proxy](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4189/console).
Could you please take a look.

### CODE REVIEW

**Comment by geliu2016** [comment]
@sandeepknd one question is the step: oc_adm_release_info need to set proxy by user in auto, is it exact? it seems that job executor have not set proxy for disconnected env.

**Comment by sandeepknd** [comment]
Hi @geliu2016 ,
Manual execution on disconnected env.
`oc debug node/<node-name>
sh-4.4# export HTTP_PROXY=http://proxy-user1:JYgU8qRZV4DY4PXJbxJK@10.0.99.4:3128
sh-4.4# export HTTPS_PROXY=http://proxy-user1:JYgU8qRZV4DY4PXJbxJK@10.0.99.4:3128
sh-4.4# oc adm release info --registry-config=/var/lib/kubelet/config.json registry.ci.openshift.org/ocp/release@sha256:a85b4266c33f36b176f601efe9d7a440505d649d62dda53b9b1055ec6051cd9b --image-for=etcd
quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ecaa970d370eb3db1e3c027a140b4ffc7a9fbe7fd4b9383b58f15b1e06819430
`

**Pull request merged**
