### PR TITLE
update for ocp-12151

### PR DESCRIPTION
**Pull request by zhouying7780**
ocp4.7 runner log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/197323/console

ocp49 cluster runner log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/197324/console

ocp48 cluster runner log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/197328/console

@kasturinarra Please help review , thanks.

### CODE REVIEW

**Comment by zhouying7780** [comment]
> @zhouying7780 could you please help update the test case in polarion as well as both of them are different currently ?

Thanks, have updated.

**Comment by zhouying7780** [comment]
@liangxia Could you please help review and merge , thanks.

**Comment by liangxia** [comment]
I'll leave it to @kasturinarra to approve

**Pull request merged**
