### PR TITLE
 Removed code , which wasnt checking status , would have passed always

### PR DESCRIPTION
**Pull request by miyadav**
thanks @sunzhaohua2 for pointing this , PTAL ..

### CODE REVIEW

**Comment by miyadav** [comment]
/hold

it gets stuck in provisioned status , checking  that again

**Comment by sunzhaohua2** [comment]
@miyadav is this same with https://bugzilla.redhat.com/show_bug.cgi?id=1905800,if so stuck in provisioned is as expected.

**Comment by miyadav** [comment]
@sunzhaohua2 @jhou1  PTAL , 

Here are the validation results - 

```
    [14:53:44] INFO> Exit Status: 0
    [14:53:44] INFO> Shell Commands: oc delete machines tenancy-dedicated-37132-szkxw --wait=false --config=/root/workdir/01ed10f32def-/ocp4_admin.kubeconfig --namespace=openshift-machine-api
    machine.machine.openshift.io "tenancy-dedicated-37132-szkxw" deleted
    
    [14:53:46] INFO> Exit Status: 0
    [14:53:47] INFO> oc get machines tenancy-dedicated-37132-szkxw --output=yaml --config=/root/workdir/01ed10f32def-/ocp4_admin.kubeconfig --namespace=openshift-machine-api
    [14:56:08] INFO> After 45 iterations and 142 seconds:
    
    STDERR:
    Error from server (NotFound): machines.machine.openshift.io "tenancy-dedicated-37132-szkxw" not found
    
    [14:56:08] INFO> Shell Commands: oc get machines tenancy-dedicated-37132-szkxw --output=yaml --config=/root/workdir/01ed10f32def-/ocp4_admin.kubeconfig --namespace=openshift-machine-api
    
    STDERR:
    Error from server (NotFound): machines.machine.openshift.io "tenancy-dedicated-37132-szkxw" not found
    
    [14:56:10] INFO> Exit Status: 1
    [14:56:10] INFO> Shell Commands: rm -r -f -- /root/workdir/01ed10f32def-
    
    [14:56:11] INFO> Exit Status: 0
    [14:56:12] INFO> === End After Scenario: Implement defaulting machineset values for AWS, Examples (#2) ===

2 scenarios (2 passed)
34 steps (34 passed)
4m39.259s
[14:56:12] INFO> === At Exit ===
```

**Comment by miyadav** [comment]
> @miyadav is this same with https://bugzilla.redhat.com/show_bug.cgi?id=1905800,if so stuck in provisioned is as expected.

@sunzhaohua2  Acknowledged , thanks! but we can have it for Provisioned for now. As m4 default value can have more than few combination which may leave it in stuck stage , there were no warning or errors in logs , we can take a look at that tommorrow.

**Comment by sunzhaohua2** [comment]
@miyadav if OCP-37132 machine status should be Running, OCP-32269 machine status should be Provisioned, we can add a column machine_status to the table.
```
    Examples:
      | name                    | file_name                 | Validation                    | machine_status |
      | default-valued-32269    | ms_default_values.yaml    | Placement                     | Provisioned    |# @case_id OCP-32269
      | tenancy-dedicated-37132 | ms_tenancy_dedicated.yaml | Tenancy:            dedicated | Running        |# @case_id OCP-37132
```

**Comment by miyadav** [comment]
> @miyadav if OCP-37132 machine status should be Running, OCP-32269 machine status should be Provisioned, we can add a column machine_status to the table.
> 
> ```
>     Examples:
>       | name                    | file_name                 | Validation                    | machine_status |
>       | default-valued-32269    | ms_default_values.yaml    | Placement                     | Provisioned    |# @case_id OCP-32269
>       | tenancy-dedicated-37132 | ms_tenancy_dedicated.yaml | Tenancy:            dedicated | Running        |# @case_id OCP-37132
> ```

Was checking this , tried by passing instance size as m5 like workers that were provisioned through installation , but it stuck in provisioned phase , with no warning or errors in logs , could be a bug ( added to bugack) .

**Comment by miyadav** [comment]
Will make few changes once this is merged - https://bugzilla.redhat.com/show_bug.cgi?id=1932154 to let this get merged and work for 4.8 regression suite

**Comment by miyadav** [comment]
@sunzhaohua2  - PTAL 
https://url.corp.redhat.com/98ac8e9

**Pull request merged**
