### PR TITLE
Fix node upgrade script

### PR DESCRIPTION
**Pull request by weinliu**
Update the securityContext part ,remove the duplicate defination

running log:
http://pastebin.test.redhat.com/1080345

### CODE REVIEW

**Comment by weinliu** [comment]
Fix the issue mentioned in https://github.com/openshift/verification-tests/pull/3109
@sunilcio @lyman9966 could you take a look?

**Comment by lyman9966** [comment]
I saw the https://github.com/openshift/verification-tests/pull/3109 mean to delete the securityContext part, but in this pr you keep the securityContext part, can you confirm it again?

**Comment by weinliu** [comment]
> securityContext

Yes, there was a duplicated securityContext session

**Comment by weinliu** [comment]
@liangxia could you help?

**Pull request merged**
