### PR TITLE
allow resizing window for Chrome

### PR DESCRIPTION
**Pull request by yasun1**
Some UI test cases are failed due to the opened window is too small to click. Require Chrome likes firefox to support resizing the window too. Please help review. Thanks.

### CODE REVIEW

**Comment by yasun1** [comment]
@yapei @xueli181114 @akostadinov Please help review.

**Comment by yapei** [comment]
@yasun1  Thank you for the changes. Can you give a jenkins pass log?

**Comment by yasun1** [comment]
I suddenly found that there is no condition(no case, no cluster, and the only way for us is ocm, but ocm code has not merged into upstream.) for me to run an automation job on jenkins. I have a try with [the ui case OCP-11219 on Prod Starter](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/75201/console), but failed with unexpected error.

@yapei  cloud you share me a case id so that I can use @xiaocwan 's config(https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/75189/rebuild/parameterized) to have a try.

**Comment by yasun1** [comment]
Works with the case OCP-25793, the jenkins log: 
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/75220/console

**Pull request merged**
