### PR TITLE
add wait for ldapserver pod Running status

### PR DESCRIPTION
**Pull request by yaoli-redhat**
@xingxingxia @pruan-rht  This PR is the cucushift/pull/8656 replacement to solve [OCPQE-3649](https://issues.redhat.com/browse/OCPQE-3649). Pass log: Runner-v3-smoke/3304, Runner-v3-smoke/3305, Runner-v3-smoke/3309, Runner-v3-smoke/3310, Runner-v3-smoke/3311 and Runner-v3-smoke/3312. Please help to review when free. Thanks!

### CODE REVIEW

**Comment by xingxingxia** [comment]
For job **Runner-v3-smoke**, to run the cases, you don't need to run via multiple jobs.
One job is enough, it self explains under the parameter in the job: `This can be any valid scenario selector understood by cucumber`. Please check.

cucumber can run: cucumber features/tierN/admin/groups_sync.feature:line1:line2:..., also can run: cucumber features/tierN/admin/groups_sync.feature, this runs all cases in a file. Please read `cucumber -h` the first a few lines.

That is, for Runner-v3-smoke, the parameter can set as same to run multiple cases.

**Comment by yaoli-redhat** [comment]
> For job **Runner-v3-smoke**, to run the cases, you don't need to run via multiple jobs.
> One job is enough, it self explains under the parameter in the job: `This can be any valid scenario selector understood by cucumber`. Please check.
> 
> cucumber can run: cucumber features/tierN/admin/groups_sync.feature:line1:line2:..., also can run: cucumber features/tierN/admin/groups_sync.feature, this runs all cases in a file. Please read `cucumber -h` the first a few lines.
> 
> That is, for Runner-v3-smoke, the parameter can set as same to run multiple cases.

Good to know that. Thanks!

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
