### PR TITLE
Moving kata features under features folder

### PR DESCRIPTION
**Pull request by valtair1891**

### CODE REVIEW

**Comment by pruan-rht** [comment]
@valtair1891 I'm ok with moving the tests to the new folder portion.  The [cluster and object files commits](https://github.com/valtair1891/verification-tests/commit/01390b0b72810c5f604c1ccbe7f44163516a4e36) should be a separate discussion/PR.

**Comment by valtair1891** [comment]
Agreed

**Comment by valtair1891** [comment]
Can you merge only kata features move?

**Comment by valtair1891** [comment]
Done

**Comment by pruan-rht** [comment]
Please squash your commits into one

**Comment by pruan-rht** [comment]
@valtair1891 I still don't understand what the is the motivation for the node.rb and cluster.rb addition.  Those operations can can be done with cucushift already, so I don't believe you need to add them.

**Comment by valtair1891** [comment]
I don't have permissions to squash commits

**Comment by pruan-rht** [comment]
@valtair1891 you can squash your own commits before submitting.  https://www.cloudbees.com/blog/git-squash-how-to-condense-your-commit-history

**Pull request closed without merging**
