### PR TITLE
Update oc downloads and license link OCP-25802

### PR DESCRIPTION
**Pull request by xiaocwan**
@yapei Please help to review. Thanks!
Passed on 4.6: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/147781/console

### CODE REVIEW

**Review by yapei — APPROVED** [review]
/lgtm

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Comment by xiaocwan** [comment]
Run a new PASS log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/149753/console

**Pull request merged**
