### PR TITLE
Adding scenario OCP-19810 for v3

### PR DESCRIPTION
**Pull request by anuragthehatter**
This is clone of PR 91 (https://github.com/openshift/verification-tests/pull/91) to be merged in v3 branch as the scenario is not supported right now on 4.x version and master now points to 4.x. All the reviewers comment has been taken care of except passing on 4.x version. The scenario is gated to be work on <=3.11 version. 
@bmeng @zhaozhanqi @pruan-rht @akostadinov 

Discussed with @bmeng and @pruan-rht.

Passing logs : https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/282/console

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
LGTM, thanks

**Comment by bmeng** [comment]
LGTM, except for some format problems.

Please do not leave the extra space(s) in the line end or the blank lines
I can see the problem in the following lines:
179 201 209 217 220 223 230 235 241 243 245 247 250 254 265 269

**Comment by anuragthehatter** [comment]
> LGTM, thanks



> LGTM, thanks

Thanks Zhanqi!

**Comment by bmeng** [comment]
The blank spaces in some lines end still not fixed.

And I did not mean we should not have blank lines in the middle of the scenario.

**Comment by anuragthehatter** [comment]
> The blank spaces in some lines end still not fixed.
> 
> And I did not mean we should not have blank lines in the middle of the scenario.

Done! PTAL

**Comment by bmeng** [comment]
LGTM thanks

**Pull request merged**
