### PR TITLE
add wait to make sure the update works

### PR DESCRIPTION
**Pull request by zhouying7780**
The case also failed with: Error from server (Conflict): Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "hooks": the object has been modified; please apply your changes to the latest version and try again 
when it run fast . so I added the wait time. 

@kasturinarra  Please help review , thanks .

### CODE REVIEW

**Comment by zhouying7780** [comment]
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245690/console

**Comment by kasturinarra** [comment]
@zhouying7780 one question, when the update fails i.e a conflict occurs does it still keep retrying with out fail when enclosed in the above wait ?

**Comment by zhouying7780** [comment]
@kasturinarra  I don't kind will have the  ' a conflict occurs' , in our case, should no conflict , only one user update the deploy.

**Comment by kasturinarra** [comment]
@zhouying7780 should we wait for a specific time instead of saying "I wait for the steps to pass" ?

**Pull request closed without merging**
