### PR TITLE
Fix resource type MachineHealthCheck

### PR DESCRIPTION
**Pull request by liangxia**
@jhou1 @akostadinov

### CODE REVIEW

**Comment by jhou1** [comment]
@liangxia Can you please provide the context as to what the problem is that this PR fixes?

**Comment by liangxia** [comment]
> @liangxia Can you please provide the context as to what the problem is that this PR fixes?

Using the same name style for all the resources.

**Comment by liangxia** [comment]
Also it's a project resource, so no need to require cluster resource.

**Comment by jhou1** [comment]
Thanks.
/lgtm

**Pull request merged**
