### PR TITLE
fix OCP-11639

### PR DESCRIPTION
**Pull request by huiran0826**
Sometimes the case failed in ci as the response code is 204, not 200, updated the code to be compatible with 204. 

Logs: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/runner-v3/317271/console

@zhaozhanqi @anuragthehatter @weliang1 @rbbratta @asood @brahaney @kedark3

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
Just wondering when it will return 204?

**Comment by huiran0826** [comment]
Currently found in this matrix  "IPI on OSP16 & FIPS on & OVN & csidriver", and it has nothing to do with egressfirewall.  Just created a pod and curl www.google.com --head, would got response as 204.

oc rsh -n test hello-pod
/ # curl www.google.com --head
HTTP/1.1 204 No Content
Date: Tue, 16 Mar 2021 10:58:23 GMT
Content-Type: text/html
Server: HTTP server (unknown)
X-XSS-Protection: 0

/ #

**Comment by rbbratta** [comment]
as long as it stays `HTTP/1.1` :smile:

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
