### PR TITLE
Fix issue for OCPQE-12378

### PR DESCRIPTION
**Pull request by XiyunZhao**
Pass log on different env:
ipi-on-gcp/versioned-installer-filestore-CSI-ci: Runner/680138/
ipi-on-aws/versioned-installer-arm-ovn-efs-sts-ci: Runner/680153/
upi-on-vsphere/versioned-installer-vmc7-secureboot_enabled-static_network:Runner/680163/
Pass log on local:
[pass.log](https://github.com/openshift/verification-tests/files/10109681/pass.log)
Pass

### CODE REVIEW

**Comment by XiyunZhao** [comment]
@yapei This PR is ready for review

**Review by yapei — COMMENTED** [review]
/lgtm

**Comment by yapei** [comment]
@liangxia  Could you help approve the fix?

**Pull request merged**
