### PR TITLE
fix intermittent test failure

### PR DESCRIPTION
**Pull request by lihongyan1**
fix intermittent test failure when integration run
https://issues.redhat.com/browse/OCPQE-231
https://issues.redhat.com/browse/OCPQE-232

### CODE REVIEW

**Comment by lihongyan1** [comment]
@juzhao @yapei Please help review

**Comment by juzhao** [comment]
Can the timeout help on the test failure?

**Comment by lihongyan1** [comment]
> Can the timeout help on the test failure?

I suppose so, they are all intermittent issue and occur when ENV is slow in the integration run. By default it check element and wait 10 seconds, if can't find, case will fail. From the screen shot, we can know element is not loaded or loaded after 10 seconds timeout

**Comment by lihongyan1** [comment]
The change is included in PR https://github.com/openshift/verification-tests/pull/1018

**Pull request closed without merging**
