### PR TITLE
update nginx-alpine image to support IPv6

### PR DESCRIPTION
**Pull request by lihongan**
enable nginx server to listen on both IPv4 and IPv6 address.

```
# oc -n hongli rsh web-server-rc-5wd86
~ $ netstat -anlp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1/nginx: master pro
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      1/nginx: master pro
tcp        0      0 :::8080                 :::*                    LISTEN      1/nginx: master pro
tcp        0      0 :::8443                 :::*                    LISTEN      1/nginx: master pro
```

@quarterpin please take a look. thanks

### CODE REVIEW

**Comment by lihongan** [comment]
log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2654/consoleFull

**Comment by quarterpin** [comment]
/lgtm

Thanks, @lihongan !

**Comment by lihongan** [comment]
@liangxia @pruan-rht please take a look. thanks

**Pull request merged**
