### PR TITLE
Use BushSlicer::HOME

### PR DESCRIPTION
**Pull request by liangxia**
/cc @pruan-rht @akostadinov

### CODE REVIEW

**Comment by akostadinov** [comment]
Actually we need  to use step `/^I obtain test data file #{QUOTED}$/`. Still this is better than before.

**Comment by pruan-rht** [comment]
That will probably be more time consuming as that will be another line to be added and change the current lines that has the HOME rereference.

**Comment by akostadinov** [comment]
I guess so. But still accessing data files in abstracted way is worth it. Another option is to write a method in `World` so that it is another `sed`. Maybe better to do that way.

**Comment by liangxia** [comment]
@akostadinov @pruan-rht  Switch to step `/^I obtain test data file #{QUOTED}$/` in https://github.com/openshift/verification-tests/pull/1227

**Pull request merged**
