### PR TITLE
add jitter to wait_for delay to reduce contention

### PR DESCRIPTION
**Pull request by rbbratta**
The `I wait up to 30 seconds for the steps to pass`
step calls `wait_for` but does not allow for changing
the interval.

The proper way to do retry loops in a distributed system is
to use jitter and/or exponential backoff as described in the Amazon paper.

https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/

Implement the Decorrelated Jitter algorithm in the wait_for
method.

### CODE REVIEW

**Comment by rbbratta** [comment]
#1649

**Comment by rbbratta** [comment]
```
ArgumentError: time interval must not be negative
verification-tests/lib/base_helper.rb:165:in `sleep'
verification-tests/lib/base_helper.rb:165:in `wait_for'
```

**Comment by pruan-rht** [comment]
@rbbratta thanks for reviving this PR.  TBH, currently we are still dealing with the cuke5 migration and might not have time to review this one.  There are a couple of questions to keep in mind for this RFE 
1. Since we use `wait_for` a lot, this is a fundamental change that needs to be tested throughly.
2. Does the benefit out-weights the risks?  What do we gain from this enhancement?  Again, the potential for breakage is pretty big.
Just a few points to think about...

**Comment by rbbratta** [comment]
not needed

**Pull request closed without merging**
