### PR TITLE
Fail ealier if package missing

### PR DESCRIPTION
**Pull request by liangxia**
@akostadinov @pruan-rht 

Idea coming from "[aos-devel] Dockerfile owners: this is better than rpm -V"

### CODE REVIEW

**Comment by akostadinov** [comment]
This is very good. There are conflicts though. Also could you update centos dockerfile as well?

**Comment by liangxia** [comment]
Rebased, and centos dockerfile updated.

**Comment by pruan-rht** [comment]
Lgtm

**Pull request merged**
