### PR TITLE
Ocp 24263 fix error sentence

### PR DESCRIPTION
**Pull request by schituku**
Runner V3 success log for last three versions
4.8
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/317584/parameters/
4.7
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/317585/parameters/
4.6
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/317586/parameters/

Raised PR#8448 in cucushift that complements this PR.

### CODE REVIEW

**Review by yapei — APPROVED** [review]
/lgtm

**Comment by yapei** [comment]
@liangxia  @pruan-rht  could you help merge? thank you

**Comment by liangxia** [comment]
There are conflicts

**Comment by pruan-rht** [comment]
/lgtm
conflicts are gone now

**Pull request merged**
