### PR TITLE
OCPQE-11705: Fix "PodSecurity violation error"

### PR DESCRIPTION
**Pull request by liangxia**
This fix the issue of:
1. I run commands on the host
2. oc debug

/cc @kasturinarra @xingxingxia @JianLi-RH @dis016 @pruan-rht @jhou1

### CODE REVIEW

**Comment by liangxia** [comment]
Test log on a 4.12 cluster,
```
    When I run commands on the host:    # features/step_definitions/node.rb:98
      | df -h / |
      [04:29:20] INFO> Shell Commands: oc get projects prj-3ba094d99a91-rootx-juym --output=yaml --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      
      STDERR:
      Error from server (NotFound): namespaces "prj-3ba094d99a91-rootx-juym" not found
      [04:29:21] INFO> Exit Status: 1
      [04:29:22] INFO> oc get projects prj-3ba094d99a91-rootx-juym --output=yaml --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      [04:29:22] INFO> After 1 iterations and 1 seconds:
      
      STDERR:
      Error from server (NotFound): namespaces "prj-3ba094d99a91-rootx-juym" not found
      [04:29:22] INFO> Shell Commands: oc new-project prj-3ba094d99a91-rootx-juym --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      Now using project "prj-3ba094d99a91-rootx-juym" on server "https://api.***.com:6443".
      
      You can add applications to this project with the 'new-app' command. For example, try:
      
          oc new-app rails-postgresql-example
      
      to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:
      
          kubectl create deployment hello-node --image=k8s.gcr.io/e2e-test-images/agnhost:2.33 -- /agnhost serve-hostname
      [04:29:24] INFO> Exit Status: 0
      [04:29:24] INFO> Shell Commands: oc get namespace prj-3ba094d99a91-rootx-juym --template=\{\{\ index\ .metadata.annotations\ \"openshift.io/sa.scc.uid-range\"\ \}\} --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      1000770000/10000
      [04:29:25] INFO> Exit Status: 0
      [04:29:25] INFO> Shell Commands: oc annotate namespace prj-3ba094d99a91-rootx-juym openshift.io/node-selector\= --overwrite=true --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      namespace/prj-3ba094d99a91-rootx-juym annotated
      [04:29:26] INFO> Exit Status: 0
      [04:29:26] INFO> Shell Commands: oc get clusterversion version -o jsonpath\=\{.status.desired.version\} --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      4.12.0-0.nightly-multi-2022-08-17-094520
      [04:29:27] INFO> Exit Status: 0
      [04:29:27] INFO> Shell Commands: oc label namespace prj-3ba094d99a91-rootx-juym security.openshift.io/scc.podSecurityLabelSync\=false --overwrite=true --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      namespace/prj-3ba094d99a91-rootx-juym labeled
      [04:29:28] INFO> Exit Status: 0
      [04:29:28] INFO> Shell Commands: oc label namespace prj-3ba094d99a91-rootx-juym pod-security.kubernetes.io/enforce\=privileged --overwrite=true --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      namespace/prj-3ba094d99a91-rootx-juym labeled
      [04:29:29] INFO> Exit Status: 0
      [04:29:29] INFO> Shell Commands: oc label namespace prj-3ba094d99a91-rootx-juym pod-security.kubernetes.io/audit\=privileged --overwrite=true --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      namespace/prj-3ba094d99a91-rootx-juym labeled
      [04:29:30] INFO> Exit Status: 0
      [04:29:30] INFO> Shell Commands: oc label namespace prj-3ba094d99a91-rootx-juym pod-security.kubernetes.io/warn\=privileged --overwrite=true --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      namespace/prj-3ba094d99a91-rootx-juym labeled
      [04:29:31] INFO> Exit Status: 0
      [04:29:31] INFO> Shell Commands: oc get projects prj-3ba094d99a91-rootx-juym --output=yaml --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: ""
          openshift.io/node-selector: ""
          openshift.io/requester: system:admin
          openshift.io/sa.scc.mcs: s0:c28,c7
          openshift.io/sa.scc.supplemental-groups: 1000770000/10000
          openshift.io/sa.scc.uid-range: 1000770000/10000
        creationTimestamp: "2022-08-24T04:27:52Z"
        labels:
          kubernetes.io/metadata.name: prj-3ba094d99a91-rootx-juym
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/enforce-version: v1.24
          pod-security.kubernetes.io/warn: privileged
          security.openshift.io/scc.podSecurityLabelSync: "false"
        name: prj-3ba094d99a91-rootx-juym
        resourceVersion: "94592"
        uid: 62cbfe1e-231b-469c-9484-5fe6f69036e4
      spec:
        finalizers:
        - kubernetes
      status:
        phase: Active
      [04:29:32] INFO> Exit Status: 0
      [04:29:32] INFO> Shell Commands: oc debug  --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig -n prj-3ba094d99a91-rootx-juym --image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8f22a1e1bd2af435082efb5d54b296b1592ba16856474a7736832891d620e6f1 node/jliu412-v45pz-master-1.c.openshift-qe.internal -- chroot /host/ bash -c mkdir\ -v\ -p\ \'/tmp/workdir/3ba094d99a91-rootx\'
      mkdir: created directory '/tmp/workdir'
      mkdir: created directory '/tmp/workdir/3ba094d99a91-rootx'
      
      STDERR:
      Starting pod/jliu412-v45pz-master-1copenshift-qeinternal-debug ...
      To use host binaries, run `chroot /host`
      
      Removing debug pod ...
      [04:29:35] INFO> Exit Status: 0
      [04:29:37] INFO> Shell Commands: oc debug  --kubeconfig=/home/jenkins/workdir/3ba094d99a91-rootx/ocp4_admin.kubeconfig -n prj-3ba094d99a91-rootx-juym --image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8f22a1e1bd2af435082efb5d54b296b1592ba16856474a7736832891d620e6f1 node/jliu412-v45pz-master-1.c.openshift-qe.internal -- chroot /host/ bash -c cd\ \'/tmp/workdir/3ba094d99a91-rootx\''
      'df\ -h\ /
      Filesystem      Size  Used Avail Use% Mounted on
      /dev/sda4       128G   15G  114G  12% /
      
      STDERR:
      Starting pod/jliu412-v45pz-master-1copenshift-qeinternal-debug ...
      To use host binaries, run `chroot /host`
      
      Removing debug pod ...
      [04:29:40] INFO> Exit Status: 0
    Then the step should succeed        # features/step_definitions/common.rb:4
```

**Comment by dis016** [comment]
LGTM

**Pull request merged**
