### PR TITLE
fix skip tour issue

### PR DESCRIPTION
**Pull request by lihongyan1**
v3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/142761/console

### CODE REVIEW

**Comment by liangxia** [comment]
@yapei  Could you help check or find some one to take a look ?

**Comment by liangxia** [comment]
Might be related with https://github.com/openshift/verification-tests/pull/1502

**Comment by yapei** [comment]
Yes, this is already fixed in #1502

**Comment by lihongyan1** [comment]
Issue is fixed and merged in https://github.com/openshift/verification-tests/pull/1502

**Review by yapei — APPROVED** [review]

**Pull request merged**
