### PR TITLE
Revert "Download webdrivers automatically"

### PR DESCRIPTION
**Pull request by liangxia**
Reverts openshift/verification-tests#3201

### CODE REVIEW

**Comment by yapei** [comment]
/remove-label lgtm
It looks like `openshift-ci/Dockerfile` is not reverted

**Comment by liangxia** [comment]
> It looks like `openshift-ci/Dockerfile` is not reverted

That file is already reverted in https://github.com/openshift/verification-tests/pull/3204

**Comment by liangxia** [comment]
Move ahead as the UI tests in Prow CI are all failing at the moment.
/approve

**Pull request merged**
