### PR TITLE
Fix image failures & output inconsistency

### PR DESCRIPTION
**Pull request by kasturinarra**
Fix image failures & change the output to match to right ones

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 could you please help review ? Thanks !!

https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/226562/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/226564/console

**Comment by kasturinarra** [comment]
@liangxia could you please help review and merge? Thanks !!

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
