### PR TITLE
Some small fix to adapt the script to the new version

### PR DESCRIPTION
**Pull request by barleyer**
Some small fix to adapt the script to the new version(the changes have already cherry pick in low versions)!

@xingxingxia @rhpmali Please review.

https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/110609/console

### CODE REVIEW

**Comment by xingxingxia** [comment]
/lgtm
BTW if not reviewed quickly due to other things could wait more time.
For fix due to version issue, same suggestion as https://github.com/openshift/cucushift/pull/7920#issuecomment-652911656 (didn't check case in Polarion)

**Comment by barleyer** [comment]
> /lgtm
> @liangxia @pruan-rht help review/merge
> For fix due to version issue, same suggestion as [openshift/cucushift#7920 (comment)](https://github.com/openshift/cucushift/pull/7920#issuecomment-652911656) (didn't check case in Polarion)
> Thanks!

Your concern is misplaced,the changes have already cherry pick in low versions, [here](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/110657/console) is the 4.2 test result.

**Pull request merged**
