### PR TITLE
cli output changed

### PR DESCRIPTION
**Pull request by pruan-rht**

### CODE REVIEW

**Comment by pruan-rht** [comment]
@akostadinov PTAL it's urgent.  The format change has been there in my 4.2.x client... I'm worried that our slaves are still using 4.1.x client for testing since automation run with Jenkins has not seen this.  Thanks!

**Comment by akostadinov** [comment]
I believe this is product bug. We need first to check if devs are going to revert. You don't just change this output from 4.2.x to 4.2.y

**Comment by akostadinov** [comment]
Also, in case we want to change on our end, we should change how we get version in the first place. This is `self.get_version_for`. It is IMO a regression to change YAML output of version between minor releases (even if you ask me between major releases).

**Comment by pruan-rht** [comment]
I'll update this PR to change the correct place today

**Comment by pruan-rht** [comment]
@akostadinov, I've fixed the `prase_version` method as well.  PTAL.  Thanks!

**Comment by pruan-rht** [comment]
https://github.com/openshift/verification-tests/pull/509

**Pull request closed without merging**
