### PR TITLE
Set skip_if_unavailable to true

### PR DESCRIPTION
**Pull request by liangxia**
Skip unavailable repositories

/cc @jhou1 @JianLi-RH @dis016 @pruan-rht

### CODE REVIEW

**Comment by jhou1** [comment]
With this change can we still successfully build the images with needed dependencies?

**Comment by liangxia** [comment]
> With this change can we still successfully build the images with needed dependencies?

It depends.  If an optional repo is unavailable, then the PR workaround that issue and moves on. But if an critical repo is unavailable, it will fail several steps further due to required dependencies can not met.

**Comment by liangxia** [comment]
/hold
Research with other ways.

**Comment by liangxia** [comment]
Prefer https://github.com/openshift/release/pull/27362

/close

**Pull request closed without merging**
