### PR TITLE
OCP-46285: fix apiServerInternalIP query for baremetal

### PR DESCRIPTION
**Pull request by rbbratta**
replace `vsphere` with a wildcard to support Baremetal

`'{.items[*].status.platformStatus.baremetal.apiServerInternalIP}'`

### CODE REVIEW

**Comment by rbbratta** [comment]
@openshift/team-sdn-qe PTAL, thanks

http://file.rdu.redhat.com/~rbrattai/logs/cucushift-2022-06-15-14-57-36.log

**Comment by anuragthehatter** [comment]
Thanks @rbbratta Metal coverage was not farsighted clearly :)

**Comment by zhaozhanqi** [comment]
thanks. 
/approve

@anuragthehatter I guess you can approve this also https://github.com/openshift/verification-tests/blob/master/features/networking/OWNERS :)

**Pull request merged**
