### PR TITLE
fix vsphere

### PR DESCRIPTION
**Pull request by ropatil010**
Hi Team, 

Kindly PTAL and review.

Failure reason: The tc uses default sc on the cluster and by default on below mentioned cluster it is with thin-csi 
TC: OCP-13390
Failure log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/816279/console 

Cluster: aos-4_11/upi-on-vsphere/versioned-installer-vmc7-disconnected-secureboot-hw18-csidriver_pvc-ci
         fips_enable: true
         Payload: 4.11.0-assembly.art6883
oc get sc | grep "default"
thin-csi (default)   csi.vsphere.vmware.com         Delete          WaitForFirstConsumer   true                   5h46m

Pass Log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/816297/console

/assign @chao007 @duanwei33 @Phaow @radeore

### CODE REVIEW

**Comment by radeore** [comment]
@ropatil010 Thanks for the fix!

Just trying to understand, one quick question, did you find any specific reason why Pod(vmdk) creation was failing with volume dynamically generated using  sc: "thin-csi",  but passed with volume generated by sc:"thin"?

**Comment by ropatil010** [comment]
Hi @radeore , 
I guess this feature works only with intree provisioner.  Plus TBH this may not be the solution i guess we should not fix this tc and remove tags 4.13, 4.14 would be good. Lets wait for team response

**Comment by duanwei33** [comment]
@ropatil010 Thanks to point out. 

(To answer @radeore 's question) In [the OCP-13390](https://github.com/openshift/cucushift/blob/master/storage/vsphere.feature#L20), we use [a in-tree pv template](https://github.com/openshift/cucushift/blob/master/testdata/storage/vsphere/myDisk.yaml) but the pv path created CSI Driver is not the same as in-tee. And we have few CI which changes the default storageclass to CSI.

From my side, this case might not be applicable when CSIMigration is enabled from 4.13 even with the fix (we even not have the in-tree storageclass), so I suggest to

- remove the tag @4.13 and @4.14 in [case OCP-13390](https://github.com/openshift/cucushift/blob/master/storage/vsphere.feature#L6)
- hold on fix(leave it there) to keep the current code shape (Seems we don't have such profile in prowCI, this is a manual launched CI in FIP test)

@ropatil010 wdyt?

**Comment by ropatil010** [comment]
Ack, Closing the PR based on discussion.

**Pull request closed without merging**
