### PR TITLE
Temp workaround for 4.4

### PR DESCRIPTION
**Pull request by liangxia**
@jhou1 @pruan-rht @akostadinov @wsun1 @dongboyan77 @xingxingxia 

Reference to `OPENSHIFTQ-12940`

### CODE REVIEW

**Comment by pruan-rht** [comment]
This looks like it's an issue with `oc` client ... we should file a bug wrt the client showing `unkown`

**Comment by liangxia** [comment]
> This looks like it's an issue with `oc` client ... we should file a bug wrt the client showing `unkown`

Yes. The problem is that when I checked locally for the image oc44, it is showing me the correct oc version info.
This is a temp workaround to unblock 4.4 testing before the issue is root identified.

**Comment by xingxingxia** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1788357#c2

**Comment by jhou1** [comment]
The bug has been fixed, but the RPM is yet not available in http://download-node-02.eng.bos.redhat.com/rcm-guest/puddles/RHAOS/AtomicOpenShift/4.4/latest/puddle.repo.
4.4 tests are still being blocked currently. 

If we don't get a build in a day or two, we may want to merge this to unblock the testing, and revert it until a newer client is ready.

**Comment by jhou1** [comment]
Per discussion with Peter, we prefer to wait for newer client.

**Comment by xingxingxia** [comment]
@zhouying7780 could you open a bug on Release Component to ART team for RPM-packed oc?

**Comment by liangxia** [comment]
Using 4.3 client for 4.4 temporarily as a workaround, closing this one.

**Pull request closed without merging**
