### PR TITLE
oapi fix

### PR DESCRIPTION
**Pull request by lyman9966**
for auto test, modify rest_openshift.rb

### CODE REVIEW

**Comment by lyman9966** [comment]
@openshift/qe-pod , pls help review

**Comment by weinliu** [comment]
@akostadinov could you help to take a look? Thanks!

**Comment by pruan-rht** [comment]
@lyman9966 @weinliu, Thank you for the PR, but I'm going to close this one because https://github.com/openshift/verification-tests/pull/88 covers all existing rest api changes.  BTW, `oapi` has been removed for 4.0.

**Comment by pruan-rht** [comment]
@lyman9966 and @weinliu  FYI, #88 has been merged.  Please file issues if you are still blocked.   Thanks!

**Pull request closed without merging**
