### PR TITLE
added @openstack-ipi and @openstack-upi tags to cases

### PR DESCRIPTION
**Pull request by JianLi-RH**
added @openstack-ipi and @openstack-upi tags to cases

/cc @jhou1 @liangxia @pruan-rht @dis016

### CODE REVIEW

**Comment by jhou1** [comment]
I think we also need `@4.9`, `@4.10` versions

**Comment by JianLi-RH** [comment]
> I think we also need `@4.9`, `@4.10` versions

Those tags already assigned to Scenario Outline

**Comment by liangxia** [comment]
@JianLi-RH There are conflicts again.
Could you fix the conflicts and let's get it fix/merge to avoid more conflicts.

**Comment by JianLi-RH** [comment]
> @JianLi-RH There are conflicts again. Could you fix the conflicts and let's get it fix/merge to avoid more conflicts.

That's because you commit "Fix tags in fsType.feature (#2367)cb95560"

**Comment by jhou1** [comment]
Looks good, please squash your commits and update your commit message to make it consistent with this PR's intention.

**Comment by JianLi-RH** [comment]
let me close this one and create a new one @jhou1 @liangxia

**Pull request closed without merging**
