### PR TITLE
add OCM login step and the env config for UI testing

### PR DESCRIPTION
**Pull request by yuwang-RH**
- Add one step definition and some rules for the ocm login.
- Add the default envs of ocm_stage and ocm_prod.
- Add the ocm_env parameter in the environment.

### CODE REVIEW

**Comment by yuwang-RH** [comment]
@yasun1 could you please help review this MR? Thanks.

**Comment by yasun1** [comment]
Please adjust the code alignment. Others LGTM.

**Comment by yuwang-RH** [comment]
@yasun1 Updated.
@akostadinov could you help review this MR? Thanks.

**Comment by akostadinov** [comment]
If I understand correctly, OCM is not an OCP cluster in any way. Just a web console. If this is correct I'll modify a little to avoid some possible confusion in the future.

**Comment by yuwang-RH** [comment]
@akostadinov You are correct, OCM is not an OCP cluster.

**Comment by yuwang-RH** [comment]
@akostadinov It there any update?  If anything needs me to change, please let me know. Thanks.

**Comment by akostadinov** [comment]
Hi, sorry for delay. Created a new class for OCM environment. It will be very messy if we need to use same class for both types of environment.

see #510

**Comment by yuwang-RH** [comment]
After the https://github.com/openshift/verification-tests/pull/510 is merged, this MR can be closed now.

**Pull request closed without merging**
