### PR TITLE
tests removed covered by ginkgo merged PRs

### PR DESCRIPTION
**Pull request by miyadav**
32269,42346,39639,48464,48463,37132
PR https://github.com/openshift/openshift-tests-private/pull/8114

PR-https://github.com/openshift/openshift-tests-private/pull/8062

PR-https://github.com/openshift/openshift-tests-private/pull/8054/

@sunzhaohua2 @huali9 @jhou1 PTAL , when time permits , there might be few issue we need to handle during cherry-pick to old < 4.10 versions.
multiple tests are covered in one PR to let us remove them from cucushift.

### CODE REVIEW

**Comment by huali9** [comment]
@miyadav seems OCP-37132 should also be removed from cucushift. It's the same as OCP-48464, right?

**Comment by miyadav** [comment]
> @miyadav seems OCP-37132 should also be removed from cucushift. It's the same as OCP-48464, right?

yes @huali9 that is WIP , will send PR asap .

**Comment by huali9** [comment]
> > @miyadav seems OCP-37132 should also be removed from cucushift. It's the same as OCP-48464, right?
> 
> yes @huali9 that is WIP , will send PR asap .

@miyadav Should it need extra new PR?

**Comment by miyadav** [comment]
we can put hold on this for now , will make another commit and unhold , thanks 
/hold

**Pull request merged**
