### PR TITLE
try to fix chrome crash issue

### PR DESCRIPTION
**Pull request by yapei**
Added `--headless` and `--disable-extensions` options when starting Chrome

### CODE REVIEW

**Comment by yapei** [comment]
I just did a regression test to make sure nothing is broken https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/768633/console 
will test the changes in Prow after it is merged

**Comment by yapei** [comment]
@liangxia  @yanpzhan Could you help review?

**Comment by yanpzhan** [comment]
I remember we meet chrome issue in prow once, and remove --headless resloved that issue. I'm wonder if there is regression issue after add the option back.

**Comment by yapei** [comment]
> I remember we met chrome issue in prow once, and remove --headless resloved that issue. I'm wonder if there is regression issue after add the option back.

Then let's try to add `--disable-extensions` option first

**Pull request merged**
