### PR TITLE
ocp 23543 - iptables binary and rules on sdn containers should be the same as host

### PR DESCRIPTION
**Pull request by anuragthehatter**
This was a test case created for SDN-341.
Logs: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/410/console
Not sure if :239 is right way to define sudo or if there is a step which can facilitate that. Pleas advise
Thanks.
@zhaozhanqi

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
LGTM,thanks

**Comment by akostadinov** [comment]
If this is a smoke test, then tag as `@smoke`. Also will iptables change if simultaneously running scenarios create projects, pods, etc? If so, then scenario needs to also be tagges as `@destructive`. I'll merge though and you can add tags according to answers of the above questions.

/lgtm

**Comment by anuragthehatter** [comment]
> If this is a smoke test, then tag as `@smoke`. Also will iptables change if simultaneously running scenarios create projects, pods, etc? If so, then scenario needs to also be tagges as `@destructive`. I'll merge though and you can add tags according to answers of the above questions.
> 
> /lgtm

Thanks for checking @akostadinov. Came back from PTO today. So this case is just checking iptables version, not changing iptables or so. So not a destructive one and smoke as well.

**Pull request merged**
