### PR TITLE
replace the image tag with digest

### PR DESCRIPTION
**Pull request by zhouying7780**
@kasturinarra Please help review , thanks .  resolve https://issues.redhat.com/browse/OCPQE-17076

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 could you help me understand how does changing tag to digest will help resolve the `no rules found error` i am confused.

**Comment by zhouying7780** [comment]
@kasturinarra The error logs show deployment not available , and I saw the cluster profile is full private , so we need to use the digest :
      [36mstatus:[0m
      [36m  conditions:[0m
      [36m  - lastTransitionTime: "2023-10-02T10:48:46Z"[0m
      [36m    lastUpdateTime: "2023-10-02T10:48:46Z"[0m
      [36m    message: Deployment does not have minimum availability.[0m
      [36m    reason: MinimumReplicasUnavailable[0m
      [36m    status: "False"[0m
      [36m    type: Available[0m
      [36m  - lastTransitionTime: "2023-10-02T10:48:36Z"[0m
      [36m    lastUpdateTime: "2023-10-02T10:48:48Z"[0m
      [36m    message: ReplicaSet "mysql-7ff568b5c4" is progressing.[0m
      [36m    reason: ReplicaSetUpdated[0m
      [36m    status: "True"[0m
      [36m    type: Progressing[0m
      [36m  observedGeneration: 4[0m
      [36m  replicas: 2[0m
      [36m  unavailableReplicas: 2[0m
      [36m  updatedReplicas: 1[0m[0m
      [36m[33m[10:53:48] INFO> Exit Status: 0[0m[0m
[31m      no rules found for option: resource_name (RuntimeError)[0m
[31m      /verification-tests/lib/rules_command_executor.rb:260:in `block (2 levels) in build_command_line'[0m
[31m      /verification-tests/lib/rules_command_executor.rb:242:in `each'[0m
[31m      /verification-tests/lib/rules_command_executor.rb:242:in `block in build_command_line'[0m
[31m      /verification-tests/lib/rules_command_executor.rb:241:in `each'[0m
[31m      /verification-tests/lib/rules_command_executor.rb:241:in `build_command_line'[0m
[31m      /verification-tests/lib/rules_command_executor.rb:53:in `run'[0m
[31m      /verification-tests/lib/cli_executor.rb:317:in `exec'[0m
[31m      /verification-tests/lib/api_accessor.rb:71:in `cli_exec'[0m
[31m      /verification-tests/lib/api_accessor_owner.rb:28:in `public_send'[0m
[31m      /verification-tests/lib/api_accessor_owner.rb:28:in `block (2 levels) in <module:APIAccessorOwner>'[0m
[31m      /verification-tests/features/step_definitions/deployment.rb:78:in `/^"(.+?)" deployment becomes ready in the(?: "(.+?)")? project$/'[0m
[31m      features/cli/oc_set_probe.feature:262:in `"mysql" deployment becomes ready in the "<%= project.name %>" project'[0m

**Pull request merged**
