### PR TITLE
OCP-22673 upgrade auto

### PR DESCRIPTION
**Pull request by xingxingxia**
Not tested yet. Pushed just for @rhpmali to reference for his upgrade case auto that is similar. After tested, will request review from @wangke19 @rhpmali

### CODE REVIEW

**Comment by xingxingxia** [comment]
The upgrade-prepare pass log: Runner-v3/89753/console
The upgrade-check pass log: Runner-v3/89793/console (public repo, therefore no full link of internal url)
@wangke19 @rhpmali help review when available, thanks.

**Comment by xingxingxia** [comment]
@wangke19 could you elaborate `different upgrade paths should have different checking points`? The PR can work for all 4.1->4.2, ..., 4.4->4.5.

**Comment by wangke19** [comment]
I am not sure the case applied on the previous upgrade paths, such 4.1-> 4.2, 4.2-> 4.3. If the case run passed on past upgrade paths. Please ignore this.

**Comment by xingxingxia** [comment]
> I am not sure the case applied on the previous upgrade paths, such 4.1-> 4.2, 4.2-> 4.3
@wangke19 , the quickest way to make assurance it, is as below: `oc adm release info quay.io/.../4.2.some_z or 4.3.some_z` to check if the PR's operator and operand images are included. The existence means no problem.

**Comment by xingxingxia** [comment]
Thanks for review.
@liangxia @akostadinov @pruan-rht please help review and merge, thanks!

**Comment by xingxingxia** [comment]
@liangxia now I rebased and resolved conflict after https://github.com/openshift/verification-tests/pull/1056 merged, please review and merge, thanks!

**Pull request merged**
