### PR TITLE
remove flake/inactive cases

### PR DESCRIPTION
**Pull request by zhaozhanqi**
@weliang1  those two cases already be marked inactive and flake,  but it's still be chosen by CI.  so here remove the script.  

Please rewrite it with golang if need. thanks.

### CODE REVIEW

**Comment by weliang1** [comment]
> @weliang1 those two cases already be marked inactive and flake, but it's still be chosen by CI. so here remove the script.
> 
> Please rewrite it with golang if need. thanks.

@zhaozhanqi These are still valid cases, but it always get unstable results in CI testing ONLY, I marked them as manual cases and keep the scripts locally, so I still can run them when I was asked to manually test them.  
It's OK for me to remove them in this PR.

**Comment by zhaozhanqi** [comment]
Thanks @weliang1 please add lgtm label and I will approve this.

**Pull request merged**
