### PR TITLE
Fix scenario dynamic provisioning

### PR DESCRIPTION
**Pull request by liangxia**
@akostadinov @pruan-rht @chao007

### CODE REVIEW

**Comment by liangxia** [comment]
Adding @jhou1 @qinpingli to review the PR as @chao007 said she have no time (busy on CSI stuff) to do the review.

**Comment by qinpingli** [comment]
@liangxia Could you add some comments for why do this change?
Seems in the OCP4.x the sc.volumeBindingMode is not "Immediate", it's just for 4.2 or both for 4.1?
Can we try to get the sc.volumeBindingMode and update the PVC binding mode with the sc.volumeBindingMode?

**Comment by liangxia** [comment]
> @liangxia Could you add some comments for why do this change?
> Seems in the OCP4.x the sc.volumeBindingMode is not "Immediate", it's just for 4.2 or both for 4.1?
> Can we try to get the sc.volumeBindingMode and update the PVC binding mode with the sc.volumeBindingMode?

@qinpingli 
The volumeBindingMode in storage class varies from platform to platform, both in 4.1 and 4.2.
To simplify the automation, we just postpone PVC status check (Check PVC status after pod is ready), so it works both for volumeBindingMode Immediate and WaitForFirstConsumer.

Also, we can get the node info where the pod is scheduled by `pod.node_name`, so store node info and labelling nodes is not need now.

Also a minor change from mypvc1/mypod1 to mypvc/mypod since we only create one pvc/pod.

**Comment by qinpingli** [comment]
@liangxia Ok, do we have cases about the volumeBindingMode? If we have, then the change LGTM.

**Comment by jhou1** [comment]
LGTM

**Comment by liangxia** [comment]
> @liangxia Ok, do we have cases about the volumeBindingMode? If we have, then the change LGTM.

Yes, they are covered in cucushift/blob/master/storage/storage_class_options.feature

**Pull request merged**
