### PR TITLE
[upgrade] Spot/preemptible instances should not block upgrade

### PR DESCRIPTION
**Pull request by sunzhaohua2**
Auto OCP-41175 Spot/preemptible instances should not block upgrade @jhou1 @miyadav please help to take a look.
Before upgrade:
```
      [06:46:51] INFO> === End After Scenario: Spot/preemptible instances should not block upgrade - prepare ===

1 scenario (1 passed)
14 steps (14 passed)
4m1.068s
```

After upgrade:
```
      [15:46:04] INFO> === End After Scenario: Spot/preemptible instances should not block upgrade ===

1 scenario (1 passed)
8 steps (8 passed)
1m40.336s
```

### CODE REVIEW

**Comment by miyadav** [comment]
@sunzhaohua2 , how are we passing prices ?

**Comment by sunzhaohua2** [comment]
@miyadav We only need to pass price on aws and azure. On gcp spot instance will be terminated after 24 hours. On aws and azure, if the price is not passed, the default price is On-Demand price.  https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/spot-instances.md#cloud-provider-implementation-specifics

**Pull request merged**
