### PR TITLE
Fix cronjob lib for 4.5

### PR DESCRIPTION
**Pull request by kasturinarra**
Fix cronjob lib for ocp4.5

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780  can you please help review, thanks !!

**Comment by akostadinov** [comment]
please also update rule 4.1 file in case this is not already done

**Comment by liangxia** [comment]
> please also update rule 4.1 file in case this is not already done

@akostadinov  We already have that in 4.1 and 4.4
```
$ grep -r 'create cron' *
lib/rules/cli/4.1.yaml:  :cmd: oc create cronjob <name> <global_options> <options>
lib/rules/cli/4.4.yaml:  :cmd: oc create cronjob <name> <global_options> <options>
lib/rules/cli/4.5.yaml:  :cmd: oc create cronjob <name>
```

**Pull request merged**
