### PR TITLE
rules update

### PR DESCRIPTION
**Pull request by yapei**
this is the rule updates and the feature fix PR is cucushift#8387

### CODE REVIEW

**Comment by yapei** [comment]
@liangxia  Could you help review and merge this one?

**Comment by liangxia** [comment]
LGTM
Still need feature team's review.

**Comment by yapei** [comment]
@liangxia  yanpzhan it taking SL this week and pass log has been given in feature update PR, no big risk

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
