### PR TITLE
update OCP-14059 to remove dependence of caddy image

### PR DESCRIPTION
**Pull request by lihongan**
log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/247789/console

@quarterpin @melvinjoseph86 @ShudiLi Please help take a look. Thanks.

### CODE REVIEW

**Comment by lihongan** [comment]
to fix https://issues.redhat.com/browse/OCPQE-7625

**Comment by quarterpin** [comment]
/lgtm
Thanks, @lihongan!

**Comment by ShudiLi** [comment]
@lihongan looks good to me, thanks.

**Pull request merged**
