### PR TITLE
add hpa_rubyex testfile

### PR DESCRIPTION
**Pull request by SSshahan**

### CODE REVIEW

**Comment by liangxia** [comment]
Where is this file used ?

**Comment by SSshahan** [comment]
my new automation case which I am working on.

**Comment by liangxia** [comment]
Then the test file should be add in the same PR with the scenario itself

**Comment by SSshahan** [comment]
does it matter? if we merge the testfile along with the scenario itself,
then we cannot give the jenkins pass log in this kind merge process.
Although we can change it to local directory when running on local host but
not sure how to do it on jenkins.

**Comment by liangxia** [comment]
>  if we merge the testfile along with the scenario itself, then we cannot give the jenkins pass log in this kind merge process.

Why not ?  The test file can be referenced by <%= ENV['BUSHSLICER_HOME'] %>/testdata/xxxxxxx

Sending test files alone make no sense, as there are no context to understand how the file is used.

**Comment by SSshahan** [comment]
OK, let me update.

**Comment by liangxia** [comment]
Adding @yapei, seems Han does not aware of OCPQE-52

**Comment by SSshahan** [comment]
I just heard of changes and i believe more of team members who did not
attend the weekly automation meeting also did not aware of the changes.

**Comment by SSshahan** [comment]
https://github.com/openshift/verification-tests/pull/852 revert pr, please help to merge. Thanks

**Comment by liangxia** [comment]
> I just heard of changes and i believe more of team members who did not attend the weekly automation meeting also did not aware of the changes.

Thank you for the remind. I just drop an email to aos-qe for awareness.

**Comment by SSshahan** [comment]
@Liang Xia <lxia@redhat.com>  seems we don't support this on 3.11, right?

**Pull request merged**
