### PR TITLE
remove tags for route whitelist tests due to ginkgo migration OCPQE-26166

### PR DESCRIPTION
**Pull request by rhamini3**
Related to task: https://issues.redhat.com/browse/OCPQE-26166

### CODE REVIEW

**Comment by rhamini3** [comment]
@lihongan @ShudiLi @melvinjoseph86 PTAL

**Comment by melvinjoseph86** [comment]
/hold
@rhamini3 you can remove the hold when the gingko PR and its cherrypick til 4.12 merges

**Comment by lihongan** [comment]
/unhold
/lgtm
Ginkgo PR is already cherry-picked to release-4.12 and got merged , see https://github.com/openshift/openshift-tests-private/pull/20859/files

**Pull request merged**
