### PR TITLE
Remove ppc64le and s390x tags for vsphere test

### PR DESCRIPTION
**Pull request by aishwaryabk**
FYI: @prb112 @juliemathew @aleskandro

### CODE REVIEW

**Comment by prb112** [comment]
/lgtm 

Per our discussion, this makes sense.

**Comment by aleskandro** [comment]
> /lgtm
> 
> Per our discussion, this makes sense.

Hi @prb112 @aishwaryabk,  could you elaborate?

I'm ok to remove them, but why a `vsphere` case is running on your envs?

**Comment by prb112** [comment]
> Scenario: OCP-37180:ClusterInfrastructure Report vCenter version to telemetry

When running locally, there is an assumption that this is vCenter. 
The tags shouldn't be applied since the test is invalid.

**Comment by aleskandro** [comment]
> When running locally, there is an assumption that this is vCenter.

This could need some better investigation, but for sure you won't need this case in your envs.

/lgtm
/assign @liangxia

**Pull request merged**
