### PR TITLE
some fixes for CI testing

### PR DESCRIPTION
**Pull request by QiaolingTang**
@akostadinov PTAL. Since @anpingli has added post actions to create the `qe-app-registry` to the clusters launched by jenkins, I modify the script to use `qe-app-registry` when there has the resources. 
Besides, there are some changes when log in to the kibana console, I add a new action to click the `Log in with OpenShift ` button if this button exists.
PTAL, thanks a lot.

### CODE REVIEW

**Comment by QiaolingTang** [comment]
Run log: https://url.corp.redhat.com/00645e3

**Comment by anpingli** [comment]
@QiaolingTang  I had created operators in post actions.    I think we needn't use the 'qe-app-registry' any more.

**Comment by QiaolingTang** [comment]
> @QiaolingTang I had created operators in post actions. I think we needn't use the 'qe-app-registry' any more.

I just set a default value for the catalog source name, if there doesn't have `qe-app-registry`, we can subscribe other sources.

**Pull request merged**
