### PR TITLE
Automate OCP-26879 till OCP-26884

### PR DESCRIPTION
**Pull request by liangxia**
Removed 4.1/4.2/4.3 from OCP-9931 in polarion.
Added OCP-26879..OCP-26884 for the checkpoints in 4.x

### CODE REVIEW

**Comment by liangxia** [comment]
After the change, the scripts are simpler, and no longer destructive.

**Comment by duanwei33** [comment]
@liangxia 
There are lots of diffs, could you attach the test log?

**Comment by liangxia** [comment]
> There are lots of diffs, could you attach the test log?

https://privatebin-it-iso.int.open.paas.redhat.com/?7684ad05313755dc#rV2jjOGlUS1hTUBYSs0MCYkTUmSI2Ec+mqpmVb5O6AQ=

**Comment by liangxia** [comment]
@pruan-rht @akostadinov  Bump.

**Pull request merged**
