### PR TITLE
Add options for 'oc adm node-logs' command

### PR DESCRIPTION
**Pull request by pdhamdhe**
@xingxingxia @xiaojiey Request you to please review and share feedback. Thanks!

### CODE REVIEW

**Comment by akostadinov** [comment]
pull request 666 seems to refuse to properly merge. Seems like some issue with git references. Could you squash your commits? If you want submit a new PR in case prow has special failure logic for this number 😁

**Comment by pdhamdhe** [comment]
@akostadinov I squashed the commits and force pushed the changes but the basic tests are still failing [ looks like pow really has special failure logic for this number :D ] Could you please check once and confirm otherwise, I will close this PR and open another one. Thanks!

**Comment by pruan-rht** [comment]
@pdhamdhe this is the error ```
{"component":"clonerefs","error":"one or more of the recor..."msg":"Failed to clone refs","time":"2020-02-04T06:38:24Z"}
error: build error: running 'umask 0002 && /clonerefs && f... -perm -0775 | xargs -r chmod g+xw' failed with exit code 1
``` . Perhaps you can try closing this PR and re-open another one instead from a clean master?

**Comment by pdhamdhe** [comment]
@pruan-rht Thanks for confirmation. I am closing this PR and will open another one soon.

**Pull request closed without merging**
