### PR TITLE
Added oc adm release info

### PR DESCRIPTION
**Pull request by rhpmali**
@xingxingxia @wangke19 please review, Thanks

### CODE REVIEW

**Comment by wangke19** [comment]
Is there any related test results? Local test also is fine.

**Comment by rhpmali** [comment]
To test this I need docker config.json credential file with docker login credential for the payload registry server, I have asked in channel for file creation, once the file is created I can come up with test results.

**Comment by xingxingxia** [comment]
Agree with @wangke19 's comment, otherwise LGTM. After updated, @ mergers to merge.

**Comment by rhpmali** [comment]
re-arranged with alphabetical order

**Comment by wangke19** [comment]
lgtm

**Pull request merged**
