### PR TITLE
Fix some failure for product change

### PR DESCRIPTION
**Pull request by lihongyan1**
Fixed some failure for product change:
Detail see https://issues.redhat.com/browse/OCPQE-10103
Jenkin job：
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/426026/console

### CODE REVIEW

**Comment by lihongyan1** [comment]
@juzhao @Tai-RedHat Please help review

**Comment by Tai-RedHat** [comment]
need test result for [OCP-43747]

**Comment by juzhao** [comment]
missed run for OCP-43747, the case passed
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/426052/console

**Comment by juzhao** [comment]
@liangxia can you approve and merge this PR?

**Pull request merged**
