### PR TITLE
Delete generated file (cluster.json) after cluster creation

### PR DESCRIPTION
**Pull request by pjanouse**

### CODE REVIEW

**Review by ppitonak — APPROVED** [review]
Works as expected.

**Comment by pjanouse** [comment]
Can someone take a look on this please? Our customers are waiting on it...

**Review by dis016 — COMMENTED** [review]
/lgtm

**Comment by ppitonak** [comment]
Who approves PRs in your team?

**Comment by dis016** [comment]
@ppitonak @liangxia approves it generally in our team.

**Pull request merged**
