### PR TITLE
add step to ensure LB is provisioned

### PR DESCRIPTION
**Pull request by lihongan**
add step to ensure LB is provisioned in upgrade with route shards case

@melvinjoseph86 @ShudiLi  please help take a look. Thanks

### CODE REVIEW

**Comment by lihongan** [comment]
log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/870500/console

**Comment by ShudiLi** [comment]
/lgtm
thanks!

**Comment by lihongan** [comment]
This is enhancement for [OCPQE-17381](https://issues.redhat.com/browse/OCPQE-17381)

**Pull request merged**
