### PR TITLE
OCM console testing support

### PR DESCRIPTION
**Pull request by akostadinov**
/hold
/assign @yuwang-RH

supersedes #469

### CODE REVIEW

**Comment by akostadinov** [comment]
In this version USERS should remain empty. You would specify users in the same way as we do for Upgrade testing. See `doc/upgrade_testing.adoc`. These can be hardcoded in `private/config/config.yaml` or specified in `BUSHSLICER_CONFIG` parameter.

Please try it out and let me know about any issues you hit!

**Comment by yuwang-RH** [comment]
@akostadinov I have a try with the user info in BUSHSLICER_CONFIG. When the script try to get user.loginname and user.password, the error bellow happens:
"can't modify frozen object (FrozenError)
      /root/ocm_ui_automation_place/verification-tests/lib/environment.rb:66:in `static_user'
"
could you help take a look?

**Comment by akostadinov** [comment]
@yuwang-RH , should be fixed now.

**Comment by yuwang-RH** [comment]
@akostadinov  Thanks. The problem is fixed now. There is one SyntaxError as my comment and other stepDefinition/rules change which I can update in another MR.

**Comment by yuwang-RH** [comment]
@akostadinov could you help take a look at my comments? Thanks.

**Comment by pruan-rht** [comment]
@yuwang-RH, can you please be more specific as to the what `SyntaxError` you mean?

**Comment by akostadinov** [comment]
@yuwang-RH  , hi, could you clarify where do you see this error as well laste some logs?

**Comment by yuwang-RH** [comment]
@akostadinov  I see this bellow error when I run script, it should be fixed by changing line56(environment.rb) ---add one bracket as opts[:web_console_url] || raise("web console URL not specified") 
`[root@yuwan verification-tests]# cucumber features/tierN/ocm/hahah.feature 
/root/ocm_ui_automation_place/verification-tests/lib/environment.rb:56: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
...pts[:web_console_url] || raise"web console URL not specified"
...                              ^ (SyntaxError)
/root/ocm_ui_automation_place/verification-tests/features/support/env.rb:17:in `require'
`

**Comment by akostadinov** [comment]
Thanks, let me know if this doesn't merge by itself soon.

**Pull request merged**
