### PR TITLE
Workaround for wrong oc client version

### PR DESCRIPTION
**Pull request by liangxia**
To support https://github.com/openshift/release/pull/51675

### CODE REVIEW

**Comment by anuragthehatter** [comment]
@liangxia Thanks Do you know how v4.2 is coming in https://github.com/openshift/release/pull/51675? I thought `env.version` should take value from OCP build version which is 4.16.

**Comment by anuragthehatter** [comment]
Also need you lgtm on https://github.com/openshift/cucushift/pull/9757. Thanks

**Comment by liangxia** [comment]
> @liangxia Thanks Do you know how v4.2 is coming in [openshift/release#51675](https://github.com/openshift/release/pull/51675)? I thought `env.version` should take value from OCP build version which is 4.16.

Same issue report 12 months ago for the wrong oc client version, https://redhat-internal.slack.com/archives/CBN38N3MW/p1684827064821489
And for `env.version`, it's reads OCP version from `oc version --client -o yaml`, because we have different cli commands in different OCP version, e.g, --config in 4.2 and earlier while its --kubeconfig in 4.3+

**Comment by anuragthehatter** [comment]
Thanks Liang

/lgtm
/approve

**Pull request merged**
