### PR TITLE
Fix rules due to OCM UI upgrading and finish some rules of OCM for new cases

### PR DESCRIPTION
**Pull request by xueli181114**
Sorry for such a huge PR, OCM UI changed a lot since PF4 upgrade, so OCM QEs did full fixing for the code and automated some cases required by the pipeline.
**Here are the changes:**
Finish rules for new cases OCP-21796 OCP-26641 OCP-26501 OCP-29668 OCP-25348 OCP-28797 OCP-33439 OCP-30503 OCP-25174 OCP-28795 OCP-27839 OCP-29426
Finish some steps due to upgrade of OCM UI
**Here are the jenkins builds:**
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/129392/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/129619/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/129719/console
@yapei @liangxia @yasun1 Could you please help to review?

### CODE REVIEW

**Comment by yapei** [comment]
@xiaocwan  Please help review

**Comment by xiaocwan** [comment]
This is all about OCM UI. Quick go through the rules, I've no objection. Also Jobs logs are PASS
/lgtm

**Pull request merged**
