### PR TITLE
Auto OCP-46244

### PR DESCRIPTION
**Pull request by huiran0826**
Auto OCP-46244 which is from customer bug.

Test Log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/3733/console
 

/cc   @openshift/team-sdn-qe

### CODE REVIEW

**Comment by anuragthehatter** [comment]
Thanks @huiran0826 

/lgtm

**Comment by zhaozhanqi** [comment]
this LGTM to me

However there is history issue is, The following step may selected one windows worker since vsphere also supported windows AFAIK. 
```
    Given I store the schedulable workers in the :workers clipboard
```
I just submit another PR for this issue 
https://github.com/openshift/verification-tests/pull/2498

**Pull request merged**
