### PR TITLE
remove tags for releases converted to GO

### PR DESCRIPTION
**Pull request by rhamini3**
Converted OCP-11635 to GO for releases 4.12-4.18
https://issues.redhat.com/browse/OCPQE-20374

### CODE REVIEW

**Comment by melvinjoseph86** [comment]
/hold
Wait till PR20473 merge til 4.12

**Comment by rhamini3** [comment]
@melvinjoseph86 this test case has already merged to 4.12, the ones in the cucushift repo have not

**Comment by melvinjoseph86** [comment]
removing hold as @rhamini3 mentioned the case is already merged til 4.12 builds.
/unhold

**Comment by lihongan** [comment]
/lgtm
Yes, other related cases are  in `cucushift` repo.

**Pull request merged**
