### PR TITLE
Update the OWNER of Logging team

### PR DESCRIPTION
**Pull request by anpingli**

### CODE REVIEW

**Comment by anpingli** [comment]
@liangxia  Could you merge it?

**Comment by QiaolingTang** [comment]
@anpingli I think I shouldn't be added as approvers

**Comment by liangxia** [comment]
> @anpingli I think I shouldn't be added as approvers

@QiaolingTang  Don't be worried. You are added as approver does not mean you are forced to approve PRs.
Take your time.

**Comment by liangxia** [comment]
/approve

You can add `/lgtm` on a separate line to get the PR merge if you have agreement on this in your subteam.

**Pull request merged**
