### PR TITLE
Adding step definitions for apiserver.rb 

### PR DESCRIPTION
**Pull request by gangwgr**
Creating step definitions for apiserver.rb regarding fix OCP-33427
Test run details - http://pastebin.test.redhat.com/1030458

### CODE REVIEW

**Comment by gangwgr** [comment]
@jmekkatt @wangke19 Please review this

**Comment by jmekkatt** [comment]
@gangwgr I think we do not need additional step definition as we are able to accommodate the fix with existing steps in framework. ( reference https://github.com/openshift/cucushift/pull/9025#discussion_r808828484)

**Comment by gangwgr** [comment]
@jmekkatt yes closing this PR

**Pull request closed without merging**
