### PR TITLE
Add rules for popover case OCP-25792

### PR DESCRIPTION
**Pull request by xiaocwan**
@SSshahan  @yapei Please review, thanks!

### CODE REVIEW

**Comment by SSshahan** [comment]
LGTM. thanks

**Comment by xiaocwan** [comment]
@pruan-rht Could you help to merge this one please since two members look good already? Thanks!

**Comment by SSshahan** [comment]
@pruan-rht  could you help  to merge it?  it will failed in ci run since the case has no relevant rules. Thanks

**Comment by xiaocwan** [comment]
@pruan-rht 
Since Two of members look good and [the feature file was merged.](https://github.com/openshift/cucushift/pull/7257)
Could you help to merge this PR plz?
Thanks

**Pull request merged**
