### PR TITLE
Add @rosa @aro @osd_ccs tag to logging acceptance case

### PR DESCRIPTION
**Pull request by anpingli**

### CODE REVIEW

**Comment by kabirbhartiRH** [comment]
Hey @anpingli Have to tried to run a smoke test on the added infra?

**Comment by anpingli** [comment]
@kabirbhartiRH  Good question. Let me confirm with osd team.

**Comment by anpingli** [comment]
@yasun1  PTAL

**Comment by yasun1** [comment]
@anpingli  Thanks. 
/lgtm

**Pull request merged**
