### PR TITLE
remove the step for deployment failure

### PR DESCRIPTION
**Pull request by zhouying7780**
to debug https://issues.redhat.com/browse/OCPQE-3204  ;
@kasturinarra   Please help review , thanks

### CODE REVIEW

**Comment by kasturinarra** [comment]
@liangxia could you please help review and approve

**Comment by liangxia** [comment]
The change will add a lot of logs in our CI, both in Prow CI and Jenkins CI. Perhaps we can add those debug steps in the test case/scenario level ?

**Comment by kasturinarra** [comment]
@zhouying7780 could you help me understand where you are adding the debug here ?

**Comment by zhouying7780** [comment]
@kasturinarra The case always failed with pod not running , actually we don't need to check the pod status , just check the probe correct is okay . so removed some steps.

**Comment by zhouying7780** [comment]
@kasturinarra At beginning I added the logs step, but liang said this will add a lot of logging , so remove it

**Comment by kasturinarra** [comment]
@zhouying7780 got it, thanks !!

**Comment by kasturinarra** [comment]
@liangxia could you please help review and approve ? thanks !!

**Pull request merged**
