### PR TITLE
Add Chrome and its driver to support web tests in Prow

### PR DESCRIPTION
**Pull request by liangxia**
/cc @jhou1 @yapei 

Steps are copied from https://github.com/openshift/verification-tests/blob/master/tools/jenkins/slaves/Dockerfile.rhel7

### CODE REVIEW

**Comment by liangxia** [comment]
Failed with "could not run steps: step src failed: the build src failed after 2m20s with reason FetchImageContentFailed: Failed to extract image content"

/retest

**Comment by liangxia** [comment]
Failed with "could not initialize namespace: could not update namespace to add labels, TTLs and active annotations: etcdserver: request timed out"

Sounds like the etcd is busy. Wait some time and then retest.

**Comment by liangxia** [comment]
Finally, the test passed.

**Comment by jhou1** [comment]
/lgtm
/approve
Thank you

**Pull request merged**
