### PR TITLE
Keep dir /var/tmp/ in image cucushift-public

### PR DESCRIPTION
**Pull request by liangxia**
/cc @pruan-rht @jhou1 @JianLi-RH @dis016

### CODE REVIEW

**Review by dis016 — COMMENTED** [review]
/lgtm

**Comment by pruan-rht** [comment]
@liangxia what's the reason for keeping that?  Just curious...

**Comment by liangxia** [comment]
> @liangxia what's the reason for keeping that? Just curious...

@pruan-rht 
Without the fix,
```
$ podman run -it --rm cucushift-public:latest bash
Cannot create a temporary file: /var/tmp/scljmGEQq
```

**Pull request merged**
