### PR TITLE
Integrate test data and test scripts

### PR DESCRIPTION
**Pull request by liangxia**
Address the issue of OCPQE-52

Only touch verification-tests part in this PR, will follow up with cucushift when we get closer to the final decision.

### CODE REVIEW

**Comment by xltian** [comment]
Do you want to add a separate folder to group all the test files? for eg: testdata?

**Comment by liangxia** [comment]
> Do you want to add a separate folder to group all the test files? for eg: testdata?

@xltian Good catch. They are grouped into the folder testdata, but forgot/lost that subpath in the substitution part.  Correct the substitution now.

**Comment by liangxia** [comment]
Merging so team can test it and report issues.

**Pull request merged**
