### PR TITLE
add oc end option for create deployment

### PR DESCRIPTION
**Pull request by zhouying7780**
@kasturinarra @liangxia Please help review . thanks

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 can you give me some background context on this PR or the command you are planning to write test case for ?

**Comment by zhouying7780** [comment]
@kasturinarra `oc create deployment` support "  Create a deployment with a command" , we need to cover it .

**Comment by kasturinarra** [comment]
@zhouying7780 thanks !!

**Comment by kasturinarra** [comment]
@zhouying7780 thanks !!

**Comment by kasturinarra** [comment]
@liangxia could you please help review and approve ? thanks !!

**Pull request merged**
