### PR TITLE
Fix OVN tests: namespace, expect grep fail, pod(0) references

### PR DESCRIPTION
**Pull request by rbbratta**
Use explicit namespace in scale commands with `-n`

Move the CNO scale to 1 register cleanup steps to before
we scale down.

It seemed like the `oc exec` commands were timing
out, so we switched to using `grep` on the server
to filter the output, but for the negative test
the `grep` will not match `"hello-pod"` so the
`oc exec` returns exit status `1`, and the step
will fail.  Adjust the steps to expect the failure.

Fix the pod references when finding the leader pods.
When we find the OVN leader pod we cache the resource
so the leader pod appears as `pod(0)`, this broke
the pod references as the `test-pods` are now
`pod(1) and pod(2)` instead of `pod(0)` and `pod(1)`.

Instead grab the pods by label and reference them that way.

### CODE REVIEW

**Comment by rbbratta** [comment]
http://file.rdu.redhat.com/~rbrattai/logs/cucushift-2020-10-13-22-37-02.log

/cc anuragthehatter
/cc zhaozhanqi
/cc huiran0826
/cc weliang1

**Comment by anuragthehatter** [comment]
Approach looks good and logs as well. Thanks Ross.

/LGTM

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
