### PR TITLE
[ONEOCPDEPL-70] Introducing OSP launcher methods for getting OSP network capacity

### PR DESCRIPTION
**Pull request by pjanouse**
- added get_network_free_capacity_by_name(osp_network_name)
- added get_network_free_capacity_by_id(osp_network_id)

### CODE REVIEW

**Comment by pjanouse** [comment]
Guys, I don't understand how it is possible but this dependency for OOD templates has never reached master of this branch. Please review and merge, it was proved as working and verified couple months ago.

**Comment by shellyyang1989** [comment]
cc @liangxia for review. Thanks!

**Pull request merged**
