### PR TITLE
Centos 8 image release recently broke the Dockerfile, need to use cen…

### PR DESCRIPTION
**Pull request by pruan-rht**
…tos:7 instead

### CODE REVIEW

**Comment by pruan-rht** [comment]
This is urgent since it's blocking other PRs from merging due to `ci/prow/images` test is failing.  Once it passes here, I'll merge it to unblock it.

**Comment by pruan-rht** [comment]
merging this PR to unblock the merge queue.

**Comment by akostadinov** [comment]
Thanks!

**Pull request merged**
