### PR TITLE
more robust hooks and fix for 4.5 console

### PR DESCRIPTION
**Pull request by akostadinov**

### CODE REVIEW

**Comment by yapei** [comment]
Thank you @akostadinov  Let me test if the fixes work

**Comment by yapei** [comment]
@akostadinov  I tried to run some tests using your branch but met this error 
```
undefined method `exec_admin' for nil:NilClass (NoMethodError)
      /home/jenkins/workspace/Runner-v3/lib/admin_credentials.rb:40:in `get'
      /home/jenkins/workspace/Runner-v3/lib/admin_credentials.rb:92:in `get'
      /home/jenkins/workspace/Runner-v3/lib/environment.rb:113:in `admin'
      /home/jenkins/workspace/Runner-v3/lib/environment.rb:283:in `get_version'
      /home/jenkins/workspace/Runner-v3/lib/environment.rb:314:in `version_cmp'
      /home/jenkins/workspace/Runner-v3/features/step_definitions/env.rb:62:in `/^the master version ([<>=]=?) "(.+?)"$/'
      features/tierN/web/admin-console/catalog.feature:6:in `Given the master version >= "4.2"'
```
details can be got from Runner-v3/93836

**Comment by akostadinov** [comment]
I don't see how any error about `exec_admin` can be related to this code change. You sure cluster was alright and your test environment setup properly?

If still doesn't work for you, please ping me with an env that makes the issue for you so I can reproduce locally.

**Comment by akostadinov** [comment]
Based on the exception I think you didn't set cluster version or you didn't provide admin kubeconfig file in your environment.

**Comment by yapei** [comment]
@akostadinov  Your fix proved to be working https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/95891/

**Pull request merged**
