### PR TITLE
fix OCP-10941

### PR DESCRIPTION
**Pull request by lyman9966**
modify image to use digest in order to run in disconnected env.
log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2207/console

@jhou1 @sunilcio @weinliu  Can you help to review? Thanks

### CODE REVIEW

**Comment by jhou1** [comment]
Has this image been mirrored?

**Comment by lyman9966** [comment]
> Has this image been mirrored?

yeah, test it pass in disconnected env

**Pull request merged**
