### PR TITLE
Added OCP-22655 scenario for Master branch

### PR DESCRIPTION
**Pull request by anuragthehatter**
Added scenario for OCP-22655. SDN services are containerized now as we know so scenario behavior should be different than v3. Also need to re-visit v3 as well
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/390/console
@zhaozhanqi

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
@anuragthehatter hi, I already automated this case, see
```
cucushift:
  file: tierN/networking/sdn.feature
  scenario: The openflow should be clear up when namespaces is deleted
```

**Comment by anuragthehatter** [comment]
> @anuragthehatter hi, I already automated this case, see
> 
> ```
> cucushift:
>   file: tierN/networking/sdn.feature
>   scenario: The openflow should be clear up when namespaces is deleted
> ```

Understand @zhaozhanqi , But this is for master branch which will target 4.0+. The exisiting scenario wont execute on 3.10+ due to SDN services are containarised post 3.10+. Let me know if i am wrong

**Comment by anuragthehatter** [comment]
> > @anuragthehatter hi, I already automated this case, see
> > ```
> > cucushift:
> >   file: tierN/networking/sdn.feature
> >   scenario: The openflow should be clear up when namespaces is deleted
> > ```
> 
> Understand @zhaozhanqi , But this is for master branch which will target 4.0+. The exisiting scenario wont execute on 3.10+ due to SDN services are containarised post 3.10+. Let me know if i am wrong



> > @anuragthehatter hi, I already automated this case, see
> > ```
> > cucushift:
> >   file: tierN/networking/sdn.feature
> >   scenario: The openflow should be clear up when namespaces is deleted
> > ```
> 
> Understand @zhaozhanqi , But this is for master branch which will target 4.0+. The exisiting scenario wont execute on 3.10+ due to SDN services are containarised post 3.10+. Let me know if i am wrong

Do you mean i should amend changes in tierN/networking/sdn.feature? for both v3 and master?

**Comment by zhaozhanqi** [comment]
> > > @anuragthehatter hi, I already automated this case, see
> > > ```
> > > cucushift:
> > >   file: tierN/networking/sdn.feature
> > >   scenario: The openflow should be clear up when namespaces is deleted
> > > ```
> > 
> > 
> > Understand @zhaozhanqi , But this is for master branch which will target 4.0+. The exisiting scenario wont execute on 3.10+ due to SDN services are containarised post 3.10+. Let me know if i am wrong
> 
> > > @anuragthehatter hi, I already automated this case, see
> > > ```
> > > cucushift:
> > >   file: tierN/networking/sdn.feature
> > >   scenario: The openflow should be clear up when namespaces is deleted
> > > ```
> > 
> > 
> > Understand @zhaozhanqi , But this is for master branch which will target 4.0+. The exisiting scenario wont execute on 3.10+ due to SDN services are containarised post 3.10+. Let me know if i am wrong
> 
> Do you mean i should amend changes in tierN/networking/sdn.feature? for both v3 and master?

yes, I think we just backport to v3 branch

**Comment by anuragthehatter** [comment]
@zhaozhanqi ahh..we may not need this PR. OCP-26555 in tierN/networking/sdn.feature is good enough to take care of this usecase on both 3.x and 4.x as i just noticed that step def is designed that way to cover all the versions. So yep, guess i will close this PR..sorry didn't realize

**Pull request closed without merging**
