### PR TITLE
Fix for stability

### PR DESCRIPTION
**Pull request by kasturinarra**
Fix the code for stability as sometimes the test case is failing with the error below
Error from server (Conflict): error when replacing "/home/jenkins/workspace/Runner-v3/testdata/deployment/updatev1.json": Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "hooks": the object has been modified; please apply your changes to the latest version and try again

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 could you please help review ? thanks !!

https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/102157/console

**Comment by zhouying7780** [comment]
@liangxia  Please help review , thanks.

**Comment by liangxia** [comment]
> Fix the code for stability as sometimes the test case is failing with the error below
> Error from server (Conflict): error when replacing "/home/jenkins/workspace/Runner-v3/testdata/deployment/updatev1.json": Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "hooks": the object has been modified; please apply your changes to the latest version and try again

This looks like a race condition issue/bug to me.

**Comment by kasturinarra** [comment]
> > Fix the code for stability as sometimes the test case is failing with the error below
> > Error from server (Conflict): error when replacing "/home/jenkins/workspace/Runner-v3/testdata/deployment/updatev1.json": Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "hooks": the object has been modified; please apply your changes to the latest version and try again
> 
> This looks like a race condition issue/bug to me.

@liangxia  Hi, i have already raised a bug for such issue and dev has closed it saying they cannot fix it see [1], fixing the automation code so that we do not see these failing.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1841552

**Comment by liangxia** [comment]
There are conflicts.

**Comment by kasturinarra** [comment]
@liangxia have resolved the conflicts, could you please help review & merge ? Thanks !!

**Pull request merged**
