### PR TITLE
Rename to consistent with repo name

### PR DESCRIPTION
**Pull request by liangxia**
I hope we will not do repo rename any more.

@akostadinov @pruan-rht @openshift/team-qe  

I'm trying to test the changes, but it requires runner-v3 parameters changes at the same time. So I skip the test/change. Maybe do that after a basic review is done here ?

How these changes are made.
```bash
# find all ruby files and replace BushSlicer to VerificationTests
Files=`find . -name "*.rb" -exec grep -l -- 'BushSlicer' {} \;`
sed -i 's/BushSlicer/VerificationTests/g' $Files
git diff
git add .

# all BushSlicer:: replace with VerificationTests::
Files=`grep -lr -- 'BushSlicer::' *`
sed -i 's/BushSlicer::/VerificationTests::/g' $Files
git diff
git add .

# all BUSHSLICER replaced with VERIFICATION_TESTS
Files=`grep -lr BUSHSLICER *`
sed -i 's/BUSHSLICER/VERIFICATION_TESTS/g' $Files
git diff
git add .

# remaining BushSlicer to verification-tests
Files=`grep -lr -- 'BushSlicer' *`
sed -i 's/BushSlicer/verification-tests/g' $Files
git diff
git add .

# remaining bushslicer...
vim `grep -rli BushSlicer * `
git diff
git add .
```

### CODE REVIEW

**Comment by pruan-rht** [comment]
According to Clayton's original comment, it was only the public repo name he objects to, he is ok with the Bushslicer reference within the codes.  I would vote for no change and reject this PR.

**Comment by akostadinov** [comment]
My bigger concern is that other teams also rely on these variables. As you said also Jenkins and prow CI jobs (although prow scripts should be part of this repo so maybe not an issue).

If we are going to change we need to discuss what exactly to change to. VERIFICATION_TESTS looks too long to me. I hoped we can have some kind of real project name. VerificationTests as a module looks too generic.

**Comment by liangxia** [comment]
How about shifthat ?

**Comment by liangxia** [comment]
So is everyone happy with `VTESTS` ?

**Comment by akostadinov** [comment]
Maybe OSVTests (OpenShift verification tests) or OKDTests? I'm voting for OKDTests.

@smarterclayton maybe you can chime in as well to say how we should name our module?

**Comment by smarterclayton** [comment]
It’s fine to call them openshift tests.  I don’t have a strong preference

**Comment by liangxia** [comment]
No longer needed. Closing.

**Pull request closed without merging**
