### PR TITLE
try to handle TERM/INT gracefully and generate vminfo.yml

### PR DESCRIPTION
**Pull request by akostadinov**
/assign @pruan-rht

### CODE REVIEW

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Comment by akostadinov** [comment]
@pruan-rht , it happened that I made some unintended changes that I reverted so your LGTM label was removed. But did you test this actually works before adding `/lgtm`?

**Comment by akostadinov** [comment]
@pruan-rht , you can spin a build, abort the build in the middle and see if vminfo is generated. Make sure that abort happens after installation steps have begun.

**Comment by akostadinov** [comment]
@pruan-rht , @jianlinliu , do you want to test this? Honestly I don't want to do myself because I need to then figure out how to remove the cluster resources in case it doesn't work :)

**Comment by pruan-rht** [comment]
@akostadinov I'll take a look at it now using your branch.

**Comment by pruan-rht** [comment]
@akostadinov hmm...it doesn't look like it worked.   https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Launch%20Environment%20Flexy/123941/.

**Comment by akostadinov** [comment]
In fact it is not necessary to trap these because `ensure` block should execute anyway. It is the way that we start our ruby process and Jenkins sending the correct signal to allow vminfo to be generated on abort.

**Comment by akostadinov** [comment]
Actually it seems to depend on `bash` mode we run installer as. So in some modes INT is ignored, in some modes TERM is ignored. To be sure proper signal handling is used instead of whatever we inherited from Bash, we need to `trap` explicitly.

**Pull request merged**
