### PR TITLE
avoid conflict with http gem

### PR DESCRIPTION
**Pull request by liangxia**
/cc @pruan-rht  @jhou1 @JianLi-RH @dis016

### CODE REVIEW

**Comment by jhou1** [comment]
Is there any context why there is such a conflict with the http gem?

**Comment by liangxia** [comment]
> Is there any context why there is such a conflict with the http gem?

@jhou1 Found the issue during testing cucushift integration with report-portal.
While we want to use our http module, http from other gems is used.

```
06-23 09:04:29.558  + bash -l -c 'bundle exec cucumber BUSHSLICER_LOG_LEVEL=debug BUSHSLICER_DEBUG_AFTER_FAIL=false rp_config=./report-portal.yml -f ReportPortal::Cucumber::Formatter -o whatever features/cli/status.feature'

06-23 09:04:34.930  Using the default, devel and _devel profiles...
06-23 09:04:34.930  Feature: Check status via oc status, wait etc
06-23 09:04:34.930  
06-23 09:04:34.930    Scenario: Show RC info and indicate bad secrets reference in 'oc status'                   # features/cli/status.feature:5
06-23 09:04:34.930  /home/jenkins/.gem/bundler/ruby/2.7.0/gems/rubytree-1.0.0/lib/tree/utils/camel_case_method_handler.rb:61:in `protected': calling protected without arguments inside a method may not have the intended effect (StructuredWarnings::BuiltInWarning)
06-23 09:04:34.930  #<Thread:0x0000000005aa4740 /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/report_portal/cucumber/formatter.rb:68 run> terminated with exception (report_on_exception is true):
06-23 09:04:34.930  /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/report_portal/http_client.rb:33:in create_client': undefined method auth' for HTTP:Module (NoMethodError)
06-23 09:04:34.930  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/report_portal/http_client.rb:7:in `initialize'
06-23 09:04:34.930  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/reportportal.rb:218:in `new'
06-23 09:04:34.930  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/reportportal.rb:218:in `http_client'
06-23 09:04:34.930  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/reportportal.rb:214:in `send_request'
06-23 09:04:34.930  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/reportportal.rb:43:in `start_launch'
06-23 09:04:34.930  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/report_portal/cucumber/messagesreport.rb:41:in `start_launch'
06-23 09:04:34.930  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/report_portal/cucumber/messagesreport.rb:25:in `initialize'
06-23 09:04:34.930  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/reportportal-1.0/lib/report_portal/cucumber
```

**Comment by pruan-rht** [comment]
@liangxia this PR from @akostadinov https://github.com/openshift/verification-tests/pull/2112 is already merged on Friday

**Comment by liangxia** [comment]
> @liangxia this PR from @akostadinov #2112 is already merged on Friday

@pruan-rht  This is for v3 branch

**Comment by pruan-rht** [comment]
/lgtm
@liangxia ok, I overlooked the branch.

**Comment by akostadinov** [comment]
@jhou1 , the conflict is only on the file name level. Our `Http` module uses our own namespace. But ruby can't differentiate between `http.rb` file and `http` gem in load path. So it will load only one of them.

**Pull request merged**
