### PR TITLE
Implementation of ovirt modules

### PR DESCRIPTION
**Pull request by santos1709**
ovirt-sdk gem being installed via Gemfile

### CODE REVIEW

**Comment by pruan-rht** [comment]
@santos1709 good new with the bundle hack your change didn't break the exiting Runner job.  @jhou1 @liangxia if you guys are ok with the change to the Runner job, then this PR can be merged.

- https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner_bundler_2_1/4/console (with bundle hack)
- https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/390320/console (ran in the current state)

**Comment by liangxia** [comment]
/hold

How do we make it to work in Prow if it needs bundle hack ?

**Comment by pruan-rht** [comment]
@liangxia can we do the following in Prow before running another other `bundle` commands?  ```gem install bundler:2.1.4; bundle _2.1.4_```

**Comment by jhou1** [comment]
@pruan-rht The Dockerfile in Prow is tools/openshift-ci/Dockerfile, can you please do the necessary change and make a PR? The bot will automatically test this.

**Comment by pruan-rht** [comment]
@jhou1 following this up...can we merge this w/o worrying about ProwCI so we can unblock @santos1709 ?

**Comment by jhou1** [comment]
I see `ovrt-engine-sdk` is successfully installed in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_verification-tests/2788/pull-ci-openshift-verification-tests-master-images/1526866335848468480/artifacts/build-logs/verification-tests.log

```
2022-05-18T10:14:50.516863873Z Fetching ovirt-engine-sdk 4.4.1
2022-05-18T10:14:50.555823562Z Installing ovirt-engine-sdk 4.4.1 with native extensions
```

This looks good to me

**Pull request merged**
