### PR TITLE
resolve failures: Failed to create index pattern app (RuntimeError)

### PR DESCRIPTION
**Pull request by QiaolingTang**
To fix failures in https://issues.redhat.com/browse/OCPQE-16096.

/cc @anpingli

### CODE REVIEW

**Comment by QiaolingTang** [comment]
Log: https://url.corp.redhat.com/56fcd99

/hold cancel

**Comment by anpingli** [comment]
@QiaolingTang  Does the historical data in ES cause the create index pattern failure?

**Comment by QiaolingTang** [comment]
> @QiaolingTang Does the historical data in ES cause the create index pattern failure?

Yes. Previously, we don't remove clusterlogging when one case is finished, and we always use same users(first, second) to test different cases in one job, thus the step fails.

**Pull request merged**
