### PR TITLE
Add upgrade-check for ocp4.3 version

### PR DESCRIPTION
**Pull request by kasturinarra**
Adding upgrade-check for ocp4.3 version as discussed here
https://coreos.slack.com/archives/CS05TR7BK/p1603350887198700

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 could you please help review ? Thanks !!

**Comment by kasturinarra** [comment]
@zhouying7780 could you please help review, thanks !!

**Comment by liangxia** [comment]
There are conflicts.

**Comment by kasturinarra** [comment]
@liangxia i have rebased and uploaded the changes, could you please help review again ? Thanks !!

**Comment by liangxia** [comment]
/hold
It looks the same as in https://github.com/openshift/verification-tests/pull/1638

**Comment by kasturinarra** [comment]
@liangxia thanks, since the other one is merged i will close this one, thanks !!

**Pull request closed without merging**
