### PR TITLE
update ES image

### PR DESCRIPTION
**Pull request by QiaolingTang**
Update ES image to fix below issue on arm64:
```
/usr/share/elasticsearch/bin/elasticsearch-env: line 67: /opt/jdk-15.0.1+9/bin/java: cannot execute binary file: Exec format error
```

/cc @anpingli @kabirbhartiRH

### CODE REVIEW

**Comment by QiaolingTang** [comment]
ARM64 log: https://url.corp.redhat.com/d3a5e72

AMD64 log: https://url.corp.redhat.com/195ef4e

**Review by anpingli — COMMENTED** [review]
/lgtm

**Pull request merged**
