### PR TITLE
[Cloud] Adding tests coverage for machine scenarios

### PR DESCRIPTION
**Pull request by jhou1**
@sunzhaohua2 @pruan-rht Would you please review? Thanks

### CODE REVIEW

**Comment by sunzhaohua2** [comment]
LGTM, thank you!

**Comment by pruan-rht** [comment]
@jhou, did you closed this PR by accident?

**Comment by jhou1** [comment]
@pruan-rht Thanks for asking. I'm making more changes, will open new PR instead.

**Comment by pruan-rht** [comment]
Ok thanks 😊

**Pull request closed without merging**
