### PR TITLE
replace etcd with codeready-toolchain-operator

### PR DESCRIPTION
**Pull request by jianzhangbjz**
As title, solve this failure: http://virt-openshift-05.lab.eng.nay.redhat.com/buildcorp/Runner-v3/77291/console

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
@akostadinov Could you help check this failure? Thanks!
```console
Build image centos from the repository expand_less | 0s
-- | --
could not wait for build: the build centos failed with reason DockerBuildFailed: Docker build strategy has failed.  + GECKODRIVER_DOWNLOAD_URL=https://github.com/vladikoff + curl -sSL https://github.com/vladikoff + bsdtar -xvf - -C /usr/local/bin bsdtar: Error opening archive: Unrecognized archive format error: build error: running 'set -x &&     SCL_BASE_PKGS="...p/epel-release-latest-7.noarch.rpm' failed with exit code 1
```

**Comment by pruan-rht** [comment]
@jianzhangbjz has this been resolved by itself?  Why did you merged this yourself after indicating there was an issue?

**Comment by jianzhangbjz** [comment]
@pruan-rht Sorry, I guess this issue still there. The same issue in #820  https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_verification-tests/820/pull-ci-openshift-verification-tests-master-images/2722
But, I don't know which server this Prow running. So, I couldn't debug/fix it. 
The reason why I force merge it is that I could not reproduce this test case issue in my local. Maybe some conflicts with etcd operator in the update CI. I just want to verify my thinking quickly.

**Comment by jianzhangbjz** [comment]
@pruan-rht Could you help share me more details about the Prow of this repo? Thanks!

**Comment by akostadinov** [comment]
I think this is an issue fixed by updated CentOS Dockerfile by @liangxia earlier this week. We need to be careful though as Peter pointed out and as @jianzhangbjz apparently was, just saying.

**Pull request merged**
