### PR TITLE
add oc adm must-gather -- /usr/bin/gather_network_ovn_trace support

### PR DESCRIPTION
**Pull request by rbbratta**
add the necessary `oc_opts_end` and `exec_command` options and make sure `<global_options>` appear first

### CODE REVIEW

**Comment by rbbratta** [comment]
```
[19:02:43] INFO> Shell Commands: oc adm must-gather  --kubeconfig=workdir/ocp4_admin.kubeconfig  --dest-dir=ovn_must_gather -- /usr/bin/gather_network_ovn_trace

[must-gather      ] OUT namespace/openshift-must-gather-6l2hx created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-7z9gj created
[must-gather-76ctj] POD INFO: Waiting for network log collection to complete ...
[must-gather-76ctj] POD INFO: Network log collection complete.
[must-gather-76ctj] POD  
[must-gather-76ctj] OUT waiting for gather to complete
[must-gather-76ctj] OUT downloading gather output
[must-gather-76ctj] OUT receiving incremental file list
[must-gather-76ctj] OUT ./
[must-gather-76ctj] OUT network_trace/
[must-gather-76ctj] OUT network_trace/ovn-startup_trace
[must-gather-76ctj] OUT network_trace/trace-20200825-190829
[must-gather-76ctj] OUT 
[must-gather-76ctj] OUT sent 73 bytes  received 62,798,579 bytes  25,119,460.80 bytes/sec
[must-gather-76ctj] OUT total size is 62,783,013  speedup is 1.00
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-7z9gj deleted
[must-gather      ] OUT namespace/openshift-must-gather-6l2hx deleted
```

**Comment by pruan-rht** [comment]
@rbbratta can you pls run it against any existing scenarios that use `oc adm` to make sure it regresses ok?

**Comment by rbbratta** [comment]
Looks like the only other test is OCP-28091 which passed

https://github.com/openshift/cucushift/blob/master/cli/oc_must-gather.feature

```

[21:28:09] INFO> Shell Commands: oc adm must-gather  --kubeconfig=workdir/ocp4_admin.kubeconfig  --dest-dir=ocp28091
[must-gather      ] OUT namespace/openshift-must-gather-85w87 created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-kfbck created
[must-gather-l6k8f] POD Wrote inspect data to must-gather.
[must-gather-l6k8f] POD Gathering data for ns/openshift-cluster-version...
[must-gather-l6k8f] POD Wrote inspect data to must-gather.
[must-gather-l6k8f] POD Gathering data for ns/openshift-config...
[must-gather-l6k8f] POD Gathering data for ns/openshift-config-managed...
[must-gather-l6k8f] POD Gathering data for ns/openshift-authentication...
[must-gather-l6k8f] POD Gathering data for ns/openshift-authentication-operator...
[must-gather-l6k8f] POD Gathering data for ns/openshift-ingress...
[must-gather-l6k8f] POD Gathering data for ns/openshift-oauth-apiserver...
[must-gather-l6k8f] POD Gathering data for ns/openshift-cloud-credential-operator...
[must-gather-l6k8f] POD Gathering data for ns/openshift-machine-api...
[must-gather-l6k8f] POD Gathering data for ns/openshift-config-operator...
```

**Pull request merged**
