### PR TITLE
add more wait time for job pod

### PR DESCRIPTION
**Pull request by zhouying7780**
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/890898/console

### CODE REVIEW

**Comment by zhouying7780** [comment]
@kasturinarra Please help review , thanks

**Comment by kasturinarra** [comment]
@zhouying7780 could you please help me understand why we are doing this ? thanks !!

**Comment by kasturinarra** [comment]
@liangxia could you please help review and approve ? thanks !!

**Pull request merged**
