### PR TITLE
report portal support

### PR DESCRIPTION
**Pull request by akostadinov**

### CODE REVIEW

**Comment by akostadinov** [comment]
@liangxia , I did local tests due to instability of PSI. Everything appears to be working alright. If you can run an actual run so then we can merge the changes, that would be of great help.

**Comment by liangxia** [comment]
Sure thing.  I'll work on it today and update results there later.

**Comment by liangxia** [comment]
Tested one test run with non-admin test cases and admin test cases, both work fine.

/lgtm

**Pull request merged**
