### PR TITLE
Stop running 100% failing test scenarios, cloud and node

### PR DESCRIPTION
**Pull request by jhou1**
According to the webapp, we have lots of 100% failure scenarios, this is a partial attempt to stop executing these tests until they have value again. Please consider re-enabling them provided they are failing due to product bugs or you have an enhancement.

cc @sunilcio @sunzhaohua2 for awareness.

### CODE REVIEW

**Comment by sunzhaohua2** [comment]
Disable these 2 cases are ok for me, as they are for upi gcp. Maybe machineset yaml files were removed on prow becasue they are upi clusters. I will set up a upi gcp cluster on prow to confirm.

**Comment by sunzhaohua2** [comment]
I submit a pr to skip the testing in such clusters, @jhou1 @pruan-rht ptal https://github.com/openshift/verification-tests/pull/3250

**Comment by jhou1** [comment]
@pruan-rht As a matter of fact, they have already been ignored for a period before being tagged flaky, so I do not consider this action to be the factor causing things to be ignored. I would not want to wait for an investigation and only worry about reducing the distractions from these unattended tests. 

Thanks for making a quick fix @sunzhaohua2 . After this is merged you can rebase and remove the tag, thank you.

**Comment by pruan-rht** [comment]
@jhou1 let's think about how to get the teams to pay attentions to these kind of low passing tests.

**Pull request merged**
