### PR TITLE
deprecated the 'new-app' command for asb/tsb test scenarios

### PR DESCRIPTION
**Pull request by bandrade**
In OCP 4.1, the new-app command has been deprecated. Like the below shows, see bug https://bugzilla.redhat.com/show_bug.cgi?id=1671528 for more details. 

By using ` When I run the :new_app client command with` we're facing the following issue:
```
STDERR:
      error: The template contained an object type unknown to `oc new-app`.  Use `oc process -f <template> | oc create -f -` instead.  Error details: no kind "ClusterServiceBroker" is registered for version "servicecatalog.k8s.io/v1beta1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
      
      [16:10:10] INFO> Exit Status: 1
      | file  | https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/svc-catalog/ups-broker-template.yaml |
      | param | UPS_BROKER_PROJECT=<%= project.name %>                                                                  |
    Then the step should succeed                                                                                # features/step_definitions/common.rb:4
      the step failed (RuntimeError)
      /home/jenkins/workspace/Runner-v3/features/step_definitions/common.rb:6:in `/^the step should( not)? (succeed|fail)$/'
      features/svc-catalog_asb/svc-catalog.feature:225:in `Then the step should succeed
```
My suggestion is to change it to `When I process and create` that will have the same expected behavior as shown below:
```
    When I process and create:                                                                                  # features/step_definitions/cli.rb:143
      [18:29:48] INFO> Shell Commands: oc process -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/svc-catalog/ups-broker-template.yaml -p UPS_BROKER_PROJECT\=up-9g --config=/home/jenkins/workspace/Runner-v3/workdir/cucushift-oc41-standard-slave-2dqdf-0/ocp4_admin.kubeconfig
      {
          "kind": "List",
          "apiVersion": "v1",
          "metadata": {},
          "items": [
              {
                  "apiVersion": "v1",
                  "kind": "Service",
                  "metadata": {
                      "labels": {
                          "app": "ups-broker",
                          "chart": "ups-broker-0.0.1",
                          "heritage": "Tiller",
                          "release": "ups-broker"
                      },
                      "name": "ups-broker"
                  },
                  "spec": {
                      "ports": [
                          {
                              "port": 80,
                              "protocol": "TCP",
                              "targetPort": 8080
                          }
                      ],
                      "selector": {
                          "app": "ups-broker"
                      },
                      "sessionAffinity": "None"
                  }
              },
              {
                  "apiVersion": "extensions/v1beta1",
                  "kind": "Deployment",
                  "metadata": {
                      "labels": {
                          "app": "ups-broker",
                          "chart": "ups-broker-0.0.1",
                          "heritage": "Tiller",
                          "release": "ups-broker"
                      },
                      "name": "ups-broker"
                  },
                  "spec": {
                      "replicas": 1,
                      "selector": {
                          "matchLabels": {
                              "app": "ups-broker"
                          }
                      },
                      "strategy": {
                          "rollingUpdate": {
                              "maxSurge": 1,
                              "maxUnavailable": 1
                          },
                          "type": "RollingUpdate"
                      },
                      "template": {
                          "metadata": {
                              "creationTimestamp": null,
                              "labels": {
                                  "app": "ups-broker",
                                  "chart": "ups-broker-0.0.1",
                                  "heritage": "Tiller",
                                  "release": "ups-broker"
                              }
                          },
                          "spec": {
                              "containers": [
                                  {
                                      "args": [
                                          "-alsologtostderr",
                                          "--port",
                                          "8080"
                                      ],
                                      "image": "quay.io/kubernetes-service-catalog/user-broker:latest",
                                      "imagePullPolicy": "Always",
                                      "livenessProbe": {
                                          "failureThreshold": 3,
                                          "initialDelaySeconds": 10,
                                          "periodSeconds": 10,
                                          "successThreshold": 1,
                                          "tcpSocket": {
                                              "port": 8080
                                          },
                                          "timeoutSeconds": 2
                                      },
                                      "name": "ups-broker",
                                      "ports": [
                                          {
                                              "containerPort": 8080,
                                              "protocol": "TCP"
                                          }
                                      ],
                                      "readinessProbe": {
                                          "failureThreshold": 1,
                                          "initialDelaySeconds": 10,
                                          "periodSeconds": 10,
                                          "successThreshold": 1,
                                          "tcpSocket": {
                                              "port": 8080
                                          },
                                          "timeoutSeconds": 2
                                      }
                                  }
                              ],
                              "dnsPolicy": "ClusterFirst",
                              "restartPolicy": "Always",
                              "terminationGracePeriodSeconds": 30
                          }
                      }
                  }
              },
              {
                  "apiVersion": "servicecatalog.k8s.io/v1beta1",
                  "kind": "ClusterServiceBroker",
                  "metadata": {
                      "name": "ups-broker"
                  },
                  "spec": {
                      "url": "http://ups-broker.up-9g.svc.cluster.local"
                  }
              }
          ]
      }
      
      [18:29:50] INFO> Exit Status: 0
```

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
LGTM, thanks!

**Comment by jianzhangbjz** [comment]
cc @chengzhang1016 @zihantang-rh from the ASB side.

**Comment by zihantang-rh** [comment]
LGTM, Thanks.

**Pull request merged**
