### PR TITLE
Scenario name change to avoid conflict

### PR DESCRIPTION
**Pull request by asood-rh**
Change the post upgrade check scenario description for test case OCP-38751 to resolve conflict another scenario name.

@zhaozhanqi 
@pruan-rht

### CODE REVIEW

**Comment by asood-rh** [comment]
Peter, this scenario name change only, can it be reviewed and merged.

/assign @pruan-rht

**Review by pruan-rht — COMMENTED** [review]
@asood-rh there's an extra space at the end of line 168...also, did you update Polarion?

**Comment by asood-rh** [comment]
@pruan-rht space is fixed. It is fixed in polarion as well in the automation script field.

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
