### PR TITLE
OCP-20688-Fix the button name by removing space from the front.

### PR DESCRIPTION
**Pull request by schituku**
Removing the space in front of the button name.

### CODE REVIEW

**Comment by yapei** [comment]
@schituku  Changes looks good, thank you. Could you give a Runner-v3 pass log to prove the fix is working?

**Comment by schituku** [comment]
@yapei The test passed on Runner-v3
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/317562/

**Comment by yapei** [comment]
great! thank you

**Review by yapei — APPROVED** [review]
/lgtm

**Comment by yapei** [comment]
@liangxia  Could you help merge this fix? Thank you

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
