### PR TITLE
merge some logging cases

### PR DESCRIPTION
**Pull request by QiaolingTang**
It takes too much time to run all the logging cases, there are some duplicated steps in many cases, to save time, merge some test cases into one case.

/cc @anpingli

### CODE REVIEW

**Comment by QiaolingTang** [comment]
Log: https://url.corp.redhat.com/9e3d4ad
/hold cancel

**Comment by QiaolingTang** [comment]
@anpingli could you please help to review this PR when you have time?

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
