### PR TITLE
Added 180 seconds of wait time in upgrade.feature

### PR DESCRIPTION
**Pull request by radeore**
Scenario updated: Cluster operator storage should be in correct status and dynamic provisioning should work well after upgrade

Execution run log: 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/389873/

Issue/bug number:
https://issues.redhat.com/browse/OCPQE-9247

### CODE REVIEW

**Comment by duanwei33** [comment]
@radeore Thanks for the update, it should help the update case (impacted by another case as mentioned in Jira)

**Comment by duanwei33** [comment]
@jhou1 PTAL, thanks.

**Comment by jhou1** [comment]
I think we need to ensure destructive tests are executed last according to the analysis in Jira. If that is implemented, do we have to add wait here?
/hold

**Pull request closed without merging**
