### PR TITLE
Add policy & pod files to test affinity & antiaffinity

### PR DESCRIPTION
**Pull request by kasturinarra**
Add policy and pod files required to test affinity & anitaffinity

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 can you please help review ? thanks !!

**Comment by liangxia** [comment]
Scenarios/scripts should go with test files in the same PR.
Can not review test files without context.

**Comment by liangxia** [comment]
Shall we close the PR as those files are included in https://github.com/openshift/cucushift/pull/7492 ?

**Comment by kasturinarra** [comment]
@liangxia yes, closing this.

**Pull request closed without merging**
