### PR TITLE
update for image pull failed

### PR DESCRIPTION
**Pull request by zhouying7780**
Fix image still use the docker.io.

### CODE REVIEW

**Comment by zhouying7780** [comment]
@kasturinarra  Please help review , thanks . 
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/232355/
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/232346/

**Comment by zhouying7780** [comment]
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/232393/console

**Comment by kasturinarra** [comment]
@liangxia could you please help review and merge ? Thanks !!

**Pull request merged**
