### PR TITLE
Update tags for FDP - OVN

### PR DESCRIPTION
**Pull request by asood-rh**
@anuragthehatter PTAL

cc @weliang1

### CODE REVIEW

**Comment by anuragthehatter** [comment]
@asood-rh Thanks. Need to hold until @weliang1 confirms all compatible to run on OVN

**Comment by asood-rh** [comment]
Sure @anuragthehatter we can wait for him to add lgtm. 
He did on slack https://redhat-internal.slack.com/archives/GLDDW02SJ/p1718900389804129?thread_ts=1718890797.907089&cid=GLDDW02SJ

FYI cc @huiran0826

**Comment by weliang1** [comment]
> Sure @anuragthehatter we can wait for him to add lgtm. He did on slack https://redhat-internal.slack.com/archives/GLDDW02SJ/p1718900389804129?thread_ts=1718890797.907089&cid=GLDDW02SJ
> 
> FYI cc @huiran0826



> @asood-rh Thanks. Need to hold until @weliang1 confirms all compatible to run on OVN

The testing summary of 7 mcast cases for the mcast bug and fixed PR
4.16 nightly build: 6 passed, OCP-12977 failed (reproduce the bug)
4.15 nightly build: all 7 passed (As bug mentioned)
4.17 nightly build: 6 passed, OCP-12977 failed (reproduce the bug)
4.16 pre-merge PR: all 7 passed (PR fixed this mcast bug)

**Pull request merged**
