### PR TITLE
add the check of clusterservicebroker before the testcases

### PR DESCRIPTION
**Pull request by emmajiafan**
Sometimes will occur the clusterservicebroker type doesn't exist. Add the resource check before test the service catalog .

### CODE REVIEW

**Comment by emmajiafan** [comment]
Please help have a review, thanks! @jianzhangbjz  @chengzhang1016

**Comment by emmajiafan** [comment]
test log:
 # @case_id OCP-15605
  @admin @destructive
  Scenario: Create/get/update/delete for ServiceBinding resource                          # features/svc-catalog_asb/svc-catalog.feature:277
      [03:04:10] INFO> === Before Scenario: Create/get/update/delete for ServiceBinding resource ===
      [03:04:10] INFO> === End Before Scenario: Create/get/update/delete for ServiceBinding resource ===
    Given I have a project                                                                # features/step_definitions/project.rb:7
      [03:04:10] INFO> HTTP GET https://api.hongli-osp44.qe.rhcloud.com:6443/.well-known/oauth-authorization-server
      [03:04:11] INFO> HTTP GET took 0.495 sec: 200 OK | application/json 621 bytes

      [03:05:09] INFO> Exit Status: 0
      [03:05:09] INFO> waiting up to 30 seconds for user clean-up to take place
      [03:05:15] INFO> REST delete_oauthaccesstoken for user 'BushSlicer::APIAccessor:testuser-47@ose', base_opts: {:options=>{:api_version=>"v1", :accept=>"application/json", :content_type=>"application/json", :oauth_token=>"LmyIHXz9lXIa2O6v0dRYwQeF-v9S9hptPXSzFqCEJsw"}, :base_url=>"https://api.hongli-osp44.qe.rhcloud.com:6443", :headers=>{"Accept"=>"<accept>", "Content-Type"=>"<content_type>", "Authorization"=>"Bearer <oauth_token>"}}, opts: {:token_to_delete=>"LmyIHXz9lXIa2O6v0dRYwQeF-v9S9hptPXSzFqCEJsw"}
      [03:05:15] INFO> HTTP DELETE https://api.hongli-osp44.qe.rhcloud.com:6443/apis/oauth.openshift.io/v1/oauthaccesstokens/LmyIHXz9lXIa2O6v0dRYwQeF-v9S9hptPXSzFqCEJsw
      [03:05:16] INFO> HTTP DELETE took 0.555 sec: 200 OK | application/json 235 bytes
      
      [03:05:16] INFO> Shell Commands: rm -r -f -- /home/jenkins/workspace/Runner-v3/workdir
      
      [03:05:16] INFO> Exit Status: 0
      [03:05:16] INFO> === End After Scenario: Create/get/update/delete for ServiceBinding resource ===

waiting for operation up to 3600 seconds..
waiting for operation up to 3600 seconds..
waiting for operation up to 3600 seconds..
waiting for operation up to 3600 seconds..

# @case_id OCP-15604
  @admin @destructive
  Scenario: Create/get/update/delete for ClusterServiceBroker resource                                    # features/svc-catalog_asb/svc-catalog.feature:134
      [03:05:16] INFO> === Before Scenario: Create/get/update/delete for ClusterServiceBroker resource ===
      [03:05:16] INFO> Shell Commands: mkdir -v -p '/home/jenkins/workspace/Runner-v3/workdir'
      mkdir: created directory '/home/jenkins/workspace/Runner-v3/workdir'
      
      [03:05:16] INFO> Exit Status: 0
      [03:05:16] INFO> === End Before Scenario: Create/get/update/delete for ClusterServiceBroker resource ===
    Given I have a project                                                                                # features/step_definitions/project.rb:7
      [03:05:16] INFO> HTTP GET https://api.hongli-osp44.qe.rhcloud.com:6443/.well-known/oauth-authorization-server
      [03:05:16] INFO> HTTP GET took 0.547 sec: 200 OK | application/json 621 bytes
# @case_id OCP-15602
  @admin @destructive
  Scenario: Create/get/update/delete for Clusterserviceclass/Clusterserviceplan resource                        # features/svc-catalog_asb/svc-catalog.feature:350
      [03:06:08] INFO> === Before Scenario: Create/get/update/delete for Clusterserviceclass/Clusterserviceplan resource ===
      [03:06:08] INFO> Shell Commands: mkdir -v -p '/home/jenkins/workspace/Runner-v3/workdir'
      mkdir: created directory '/home/jenkins/workspace/Runner-v3/workdir'
      
      [03:06:08] INFO> Exit Status: 0
      [03:06:08] INFO> === End Before Scenario: Create/get/update/delete for Clusterserviceclass/Clusterserviceplan resource ===
    Given I have a project                                                                                      # features/step_definitions/project.rb:7
      [03:06:08] INFO> HTTP GET https://api.hongli-osp44.qe.rhcloud.com:6443/.well-known/oauth-authorization-server
      [03:06:09] INFO> HTTP GET took 0.520 sec: 200 OK | application/json 621 bytes
# @case_id OCP-15603
  @admin @destructive
  Scenario: Create/get/update/delete for ServiceInstance resource                   # features/svc-catalog_asb/svc-catalog.feature:218
      [03:07:17] INFO> === Before Scenario: Create/get/update/delete for ServiceInstance resource ===
      [03:07:17] INFO> Shell Commands: mkdir -v -p '/home/jenkins/workspace/Runner-v3/workdir'
      mkdir: created directory '/home/jenkins/workspace/Runner-v3/workdir'
      
      [03:07:17] INFO> Exit Status: 0
      [03:07:17] INFO> === End Before Scenario: Create/get/update/delete for ServiceInstance resource ===
    Given I have a project                                                          # features/step_definitions/project.rb:7
      [03:07:17] INFO> HTTP GET https://api.hongli-osp44.qe.rhcloud.com:6443/.well-known/oauth-authorization-server
      [03:07:18] INFO> HTTP GET took 0.474 sec: 200 OK | application/json 621 bytes
   [03:08:19] INFO> Exit Status: 0
      [03:08:19] INFO> waiting up to 30 seconds for user clean-up to take place
      [03:08:26] INFO> REST delete_oauthaccesstoken for user 'BushSlicer::APIAccessor:testuser-47@ose', base_opts: {:options=>{:api_version=>"v1", :accept=>"application/json", :content_type=>"application/json", :oauth_token=>"XGM9hPPZmY_55KOgPwBHG9BCsWA-J5ddQMnKxeV4JJY"}, :base_url=>"https://api.hongli-osp44.qe.rhcloud.com:6443", :headers=>{"Accept"=>"<accept>", "Content-Type"=>"<content_type>", "Authorization"=>"Bearer <oauth_token>"}}, opts: {:token_to_delete=>"XGM9hPPZmY_55KOgPwBHG9BCsWA-J5ddQMnKxeV4JJY"}
      [03:08:26] INFO> HTTP DELETE https://api.hongli-osp44.qe.rhcloud.com:6443/apis/oauth.openshift.io/v1/oauthaccesstokens/XGM9hPPZmY_55KOgPwBHG9BCsWA-J5ddQMnKxeV4JJY
      [03:08:27] INFO> HTTP DELETE took 0.478 sec: 200 OK | application/json 235 bytes
      
      [03:08:27] INFO> Shell Commands: rm -r -f -- /home/jenkins/workspace/Runner-v3/workdir
      
      [03:08:27] INFO> Exit Status: 0
      [03:08:27] INFO> === End After Scenario: Create/get/update/delete for ServiceInstance resource ===

4 scenarios (4 passed)
103 steps (103 passed)
4m19.011s

**Comment by emmajiafan** [comment]
test log:
 # @case_id OCP-15605
  @admin @destructive
  Scenario: Create/get/update/delete for ServiceBinding resource                          # features/svc-catalog_asb/svc-catalog.feature:277
      [03:04:10] INFO> === Before Scenario: Create/get/update/delete for ServiceBinding resource ===
      [03:04:10] INFO> === End Before Scenario: Create/get/update/delete for ServiceBinding resource ===
    Given I have a project                                                                # features/step_definitions/project.rb:7
      [03:04:10] INFO> HTTP GET https://api.hongli-osp44.qe.rhcloud.com:6443/.well-known/oauth-authorization-server
      [03:04:11] INFO> HTTP GET took 0.495 sec: 200 OK | application/json 621 bytes

      [03:05:09] INFO> Exit Status: 0
      [03:05:09] INFO> waiting up to 30 seconds for user clean-up to take place
      [03:05:15] INFO> REST delete_oauthaccesstoken for user 'BushSlicer::APIAccessor:testuser-47@ose', base_opts: {:options=>{:api_version=>"v1", :accept=>"application/json", :content_type=>"application/json", :oauth_token=>"LmyIHXz9lXIa2O6v0dRYwQeF-v9S9hptPXSzFqCEJsw"}, :base_url=>"https://api.hongli-osp44.qe.rhcloud.com:6443", :headers=>{"Accept"=>"<accept>", "Content-Type"=>"<content_type>", "Authorization"=>"Bearer <oauth_token>"}}, opts: {:token_to_delete=>"LmyIHXz9lXIa2O6v0dRYwQeF-v9S9hptPXSzFqCEJsw"}
      [03:05:15] INFO> HTTP DELETE https://api.hongli-osp44.qe.rhcloud.com:6443/apis/oauth.openshift.io/v1/oauthaccesstokens/LmyIHXz9lXIa2O6v0dRYwQeF-v9S9hptPXSzFqCEJsw
      [03:05:16] INFO> HTTP DELETE took 0.555 sec: 200 OK | application/json 235 bytes
      
      [03:05:16] INFO> Shell Commands: rm -r -f -- /home/jenkins/workspace/Runner-v3/workdir
      
      [03:05:16] INFO> Exit Status: 0
      [03:05:16] INFO> === End After Scenario: Create/get/update/delete for ServiceBinding resource ===

waiting for operation up to 3600 seconds..
waiting for operation up to 3600 seconds..
waiting for operation up to 3600 seconds..
waiting for operation up to 3600 seconds..

# @case_id OCP-15604
  @admin @destructive
  Scenario: Create/get/update/delete for ClusterServiceBroker resource                                    # features/svc-catalog_asb/svc-catalog.feature:134
      [03:05:16] INFO> === Before Scenario: Create/get/update/delete for ClusterServiceBroker resource ===
      [03:05:16] INFO> Shell Commands: mkdir -v -p '/home/jenkins/workspace/Runner-v3/workdir'
      mkdir: created directory '/home/jenkins/workspace/Runner-v3/workdir'
      
      [03:05:16] INFO> Exit Status: 0
      [03:05:16] INFO> === End Before Scenario: Create/get/update/delete for ClusterServiceBroker resource ===
    Given I have a project                                                                                # features/step_definitions/project.rb:7
      [03:05:16] INFO> HTTP GET https://api.hongli-osp44.qe.rhcloud.com:6443/.well-known/oauth-authorization-server
      [03:05:16] INFO> HTTP GET took 0.547 sec: 200 OK | application/json 621 bytes
# @case_id OCP-15602
  @admin @destructive
  Scenario: Create/get/update/delete for Clusterserviceclass/Clusterserviceplan resource                        # features/svc-catalog_asb/svc-catalog.feature:350
      [03:06:08] INFO> === Before Scenario: Create/get/update/delete for Clusterserviceclass/Clusterserviceplan resource ===
      [03:06:08] INFO> Shell Commands: mkdir -v -p '/home/jenkins/workspace/Runner-v3/workdir'
      mkdir: created directory '/home/jenkins/workspace/Runner-v3/workdir'
      
      [03:06:08] INFO> Exit Status: 0
      [03:06:08] INFO> === End Before Scenario: Create/get/update/delete for Clusterserviceclass/Clusterserviceplan resource ===
    Given I have a project                                                                                      # features/step_definitions/project.rb:7
      [03:06:08] INFO> HTTP GET https://api.hongli-osp44.qe.rhcloud.com:6443/.well-known/oauth-authorization-server
      [03:06:09] INFO> HTTP GET took 0.520 sec: 200 OK | application/json 621 bytes
# @case_id OCP-15603
  @admin @destructive
  Scenario: Create/get/update/delete for ServiceInstance resource                   # features/svc-catalog_asb/svc-catalog.feature:218
      [03:07:17] INFO> === Before Scenario: Create/get/update/delete for ServiceInstance resource ===
      [03:07:17] INFO> Shell Commands: mkdir -v -p '/home/jenkins/workspace/Runner-v3/workdir'
      mkdir: created directory '/home/jenkins/workspace/Runner-v3/workdir'
      
      [03:07:17] INFO> Exit Status: 0
      [03:07:17] INFO> === End Before Scenario: Create/get/update/delete for ServiceInstance resource ===
    Given I have a project                                                          # features/step_definitions/project.rb:7
      [03:07:17] INFO> HTTP GET https://api.hongli-osp44.qe.rhcloud.com:6443/.well-known/oauth-authorization-server
      [03:07:18] INFO> HTTP GET took 0.474 sec: 200 OK | application/json 621 bytes
   [03:08:19] INFO> Exit Status: 0
      [03:08:19] INFO> waiting up to 30 seconds for user clean-up to take place
      [03:08:26] INFO> REST delete_oauthaccesstoken for user 'BushSlicer::APIAccessor:testuser-47@ose', base_opts: {:options=>{:api_version=>"v1", :accept=>"application/json", :content_type=>"application/json", :oauth_token=>"XGM9hPPZmY_55KOgPwBHG9BCsWA-J5ddQMnKxeV4JJY"}, :base_url=>"https://api.hongli-osp44.qe.rhcloud.com:6443", :headers=>{"Accept"=>"<accept>", "Content-Type"=>"<content_type>", "Authorization"=>"Bearer <oauth_token>"}}, opts: {:token_to_delete=>"XGM9hPPZmY_55KOgPwBHG9BCsWA-J5ddQMnKxeV4JJY"}
      [03:08:26] INFO> HTTP DELETE https://api.hongli-osp44.qe.rhcloud.com:6443/apis/oauth.openshift.io/v1/oauthaccesstokens/XGM9hPPZmY_55KOgPwBHG9BCsWA-J5ddQMnKxeV4JJY
      [03:08:27] INFO> HTTP DELETE took 0.478 sec: 200 OK | application/json 235 bytes
      
      [03:08:27] INFO> Shell Commands: rm -r -f -- /home/jenkins/workspace/Runner-v3/workdir
      
      [03:08:27] INFO> Exit Status: 0
      [03:08:27] INFO> === End After Scenario: Create/get/update/delete for ServiceInstance resource ===

4 scenarios (4 passed)
103 steps (103 passed)
4m19.011s

**Comment by emmajiafan** [comment]
@akostadinov @pruan-rht Please help have a review, thanks!

**Comment by chengzhang1016** [comment]
LGTM. Thanks.,

**Comment by emmajiafan** [comment]
Hi @akostadinov @pruan-rht Could you help take a look at this PR? And help add "approved" "lgtm" label if it is ok? Thanks!

**Comment by pruan-rht** [comment]
@emmajiafan alternatively you can do these two lines.  ```
Given evaluation of `BushSlicer::ClusterServiceBroker.list(user: admin)` is stored in the clipboard
And the expression should be true>$result[:success]
```

**Pull request merged**
