### PR TITLE
OCP_11565_Fix help output issue

### PR DESCRIPTION
**Pull request by weinliu**
@jhou1 @sunilcio @lyman9966 could you help take a look?
log:  http://pastebin.test.redhat.com/886545

### CODE REVIEW

**Comment by sunilcio** [comment]
LGTM. However I want to discuss if we can deprecate this case as I see it is just checking oc secret help output which I guess is not adding much value. @jhou1 @lyman9966 hi, also need your opinion.

**Comment by weinliu** [comment]
> LGTM. However I want to discuss if we can deprecate this case as I see it is just checking oc secret help output which I guess is not adding much value. @jhou1 @lyman9966 hi, also need your opinion.

Yes...Before fixing this, I also had a plan B of deprecating it.

**Comment by jhou1** [comment]
+1, this test does not have much value for us.

**Comment by lyman9966** [comment]
+1 I agree with the deprecation plan. It's not so valuable and for the help output may change in future version, it may bring more maintenance cost.

**Comment by weinliu** [comment]
Inactive the case as discussed.

**Pull request closed without merging**
