### PR TITLE
Fix the automation issue found in aws test

### PR DESCRIPTION
**Pull request by qinpingli**
@duanwei33 @chao007 Please help review.

### CODE REVIEW

**Comment by duanwei33** [comment]
@qinpingli Could you adjust the format in NoDiskConflict.feature like line 23-24, 28-29, 33-34? Others LGTM.

**Comment by qinpingli** [comment]
@duanwei33 Thanks for the review. Updated.

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
