### PR TITLE
Adding support for oc create_deployment

### PR DESCRIPTION
**Pull request by kasturinarra**
Adding support for oc create_deployment to fix test case OCP-15156

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 @xingxingxia can you please help review ?

**Comment by liangxia** [comment]
LGTM. We also need to add this to 4.4.yaml

**Comment by kasturinarra** [comment]
> LGTM. We also need to add this to 4.4.yaml

sure, will add one and send a pr

**Pull request merged**
