### PR TITLE
Tag network-multitenant test case

### PR DESCRIPTION
**Pull request by jhou1**
This resolves OCPQE-5737.

Once tag is added, the test is skipped from Prow. Former failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21988/rehearse-21988-periodic-ci-openshift-verification-tests-master-4.9-e2e-cucushift-gcp-ipi/1440601527981969408

@liangxia @zhaozhanqi PTAL

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
@jhou1 thanks for implement this.  So I need to update `@network-multitenant` for multitenant script, right?

**Comment by jhou1** [comment]
Thank you @zhaozhanqi , please help us update those when you've got time, it will help us a lot in our future work!

**Comment by zhaozhanqi** [comment]
> Thank you @zhaozhanqi , please help us update those when you've got time, it will help us a lot in our future work!
yes, sure. file another one https://github.com/openshift/cucushift/pull/8776

**Pull request merged**
