### PR TITLE
update the ip bin path

### PR DESCRIPTION
**Pull request by zhaozhanqi**
1 update `/usr/sbin/ip` to `/sbin/ip`
2. update the net_admin_cap_pod.yaml file with origin image to use `conntrack`

@weliang1 @anuragthehatter @huiran0826 @rbbratta 
PTAL, thanks

### CODE REVIEW

**Comment by weliang1** [comment]
/LGTM
Better to have testing log link

**Comment by pruan-rht** [comment]
@zhaozhanqi LG, can you perhaps add the reason for the update and whether or not it affects backward compatibilty?

**Comment by zhaozhanqi** [comment]
> @zhaozhanqi LG, can you perhaps add the reason for the update and whether or not it affects backward compatibilty?
we changed the image and the ping path is in '/sbin/' of new image

**Comment by anuragthehatter** [comment]
@zhaozhanqi That looks good to me unless if you think its okay to just use ```ip``` instead of full path. This will shield us in making such changes again in future as binary will point to default path always IMO.

**Comment by liangxia** [comment]
> just use `ip` instead of full path

+1 for this

**Comment by zhaozhanqi** [comment]
> @zhaozhanqi That looks good to me unless if you think its okay to just use `ip` instead of full path. This will shield us in making such changes again in future as binary will point to default path always IMO.

yes, have no idea the background why use the full path before.  use 'ip' should more flex 
updated all. thanks.

**Comment by zhaozhanqi** [comment]
> > just use `ip` instead of full path
> 
> +1 for this
updated, thanks

**Pull request merged**
