### PR TITLE
OVN: use ip6tables for IPv6 addresses

### PR DESCRIPTION
**Pull request by rbbratta**
For split brain we DROP packes from peer master, but for IPv6
addresses we need to use `ip6tables` command

### CODE REVIEW

**Comment by rbbratta** [comment]
@openshift/team-sdn-qe PTAL, thanks

http://file.rdu.redhat.com/~rbrattai/logs/cucushift-2022-05-23-17-08-33.log

**Comment by anuragthehatter** [comment]
/lgtm
Thanks @rbbratta

**Pull request merged**
