### PR TITLE
update routing dc apiVersion

### PR DESCRIPTION
**Pull request by lihongan**
@quarterpin @melvinjoseph86 @ShudiLi PTAL, thanks

### CODE REVIEW

**Comment by lihongan** [comment]
logs: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/400563/console

**Comment by lihongan** [comment]
```
04-22 18:17:48.920      Given I obtain test data file "routing/header-test/dc.json"                           # features/step_definitions/file.rb:1
04-22 18:17:49.177      When I run the :create client command with:                                           # features/step_definitions/cli.rb:13
04-22 18:17:49.177        | f  |   dc.json  |
04-22 18:17:49.177        [10:17:47] INFO> Shell Commands: oc create -f dc.json --kubeconfig=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_testuser-38.kubeconfig
04-22 18:17:49.177        deploymentconfig.apps.openshift.io/header-test created
```

**Comment by quarterpin** [comment]
looks good! thanks @lihongan!

**Pull request merged**
