### PR TITLE
fix: Error from server (NotFound): namespaces "aos-qe-ci" not found

### PR DESCRIPTION
**Pull request by QiaolingTang**
Fix issue when deploy logging operators:
```
[2021-07-02T00:47:57.737Z] [36m[33m[00:47:56] INFO> Shell Commands: oc get packagemanifests cluster-logging --output=yaml --config=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_admin.kubeconfig[0m[0m
[2021-07-02T00:47:57.737Z] [36m[0m
[2021-07-02T00:47:57.737Z] [36mSTDERR:[0m
[2021-07-02T00:47:57.737Z] [36mError from server (NotFound): namespaces "aos-qe-ci" not found[0m
```

### CODE REVIEW

**Comment by anpingli** [comment]
@QiaolingTang  I had noticed that for time. Thanks for your PR.

**Review by anpingli — COMMENTED** [review]
/lgtm

**Comment by liangxia** [comment]
The issue is that we are running on dynamic agents provisioned on a OCP cluster. So the agent itself connects to the OCP cluster (under project aos-qe-ci), and in the agent, oc client connect to the testing cluster.  When the context is not clear enough, it got confused, and will use the default project from service account, which is project aos-qe-ci.

You got it right, explicitly switch the project will solve the issue, as in this way, the project info is written into the user's kubeconfig

**Pull request merged**
