### PR TITLE
Fix apiVersion

### PR DESCRIPTION
**Pull request by liangxia**
/cc @jhou1 @JianLi-RH @dis016 @pruan-rht

### CODE REVIEW

**Comment by dis016** [comment]
LGTM

**Comment by pruan-rht** [comment]
@liangxia curious, why is it necessary to remove the `"`?  I think for XML, it should work either way.

**Comment by liangxia** [comment]
> @liangxia curious, why is it necessary to remove the `"`? I think for XML, it should work either way.

Those test files set an bad example of mixture use of json/yaml in one test file. It makes future batch update more difficult.

**Pull request merged**
