### PR TITLE
[Automate-storage] [OCP-44578] [AWS-EBS-CSI] [Snapshot operator]

### PR DESCRIPTION
**Pull request by ropatil010**
Adding the case id. 

/cc @duanwei33  @jhou1

### CODE REVIEW

**Comment by jhou1** [comment]
Please update the PR summary and commit message to describe what this does.
/hold

**Review by ropatil010 — COMMENTED** [review]
Adding Testcase ID for [AWS-EBS-CSI] [Snapshot operator]

**Pull request merged**
