### PR TITLE
fix OCP-20849 search_image for input_value xpath and search button removed issue

### PR DESCRIPTION
**Pull request by xiaocwan**
1) input_value xpath changed
2) page form changed, Search button has been removed, clicking anywhere else takes place for Search button. Here I click the radio button 
@SSshahan Please review. Thanks!
PASS locally on Firefox http://pastebin.test.redhat.com/842577

### CODE REVIEW

**Comment by SSshahan** [comment]
@xiaocwan  please give the jenkins pass log then I'll tag lgtm

**Comment by xiaocwan** [comment]
@SSshahan https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/75228/console

**Pull request merged**
