### PR TITLE
auto for OCP-33209

### PR DESCRIPTION
**Pull request by zhouying7780**
prepare job: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/123652/console
check job: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/123956/console

@kasturinarra Could you please help review , thanks.

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 i am just wondering how is it different from the already existing upgrade ?  could you please help explain ? Also it would be good to add some notes in the 'Description' field which will be helpful for reviewer to understand what and why the change is for , thanks !!

**Comment by zhouying7780** [comment]
@kasturinarra  `oc new-app` has changed to create deployment instead of "DC" by default, so need to split to a new case for OCP4.6 +

**Comment by kasturinarra** [comment]
@zhouying7780 please help add version check for already existing case and raise a PR, thanks !!

**Comment by liangxia** [comment]
You can update existing one from `new_app` to `new_app_as_dc`.   The `new_app_as_dc` use `oc new-app` in version <= 4.4, and use `oc new-app --as-deployment-config` in version >= 4.5

**Pull request merged**
