### PR TITLE
Remove special char from Scenario name and sync tags

### PR DESCRIPTION
**Pull request by liangxia**
The `[]` are special character in regexp, remove them from the scenario name so that  several tools rely on regexp works.

Will sync the scenario name change back to Polarion after PR merge.

/cc @ropatil010 @duanwei33 @kasturinarra @jhou1 @JianLi-RH @dis016 @pruan-rht

### CODE REVIEW

**Comment by dis016** [comment]
LGTM

**Comment by duanwei33** [comment]
Acked, thanks.

**Comment by liangxia** [comment]
Polarion automation field are updated, too.

**Pull request merged**
