### PR TITLE
fix failure when checking prometheus metrics

### PR DESCRIPTION
**Pull request by QiaolingTang**
Fix below failure when testing on OCP 4.11:
```
      [01:31:54] INFO> Shell Commands: oc project openshift-monitoring --kubeconfig=/Users/qitang/workdir/Qiaolings-MacBook-Pro-RH-qitangx/ocp4_testuser-22.kubeconfig
      Already on project "openshift-monitoring" on server "https://api.xxxx.xxxx.openshift.com:6443".
      INFO> last 3 messages repeated 103 times
      [01:37:49] INFO> Exit Status: 0
      what Secret are you talking about? (RuntimeError)
      /Users/qitang/go/src/github.com/openshift/verification-tests/lib/world.rb:321:in `project_resource'
      /Users/qitang/go/src/github.com/openshift/verification-tests/lib/world.rb:149:in `secret'
      /Users/qitang/go/src/github.com/openshift/verification-tests/features/step_definitions/prometheus.rb:11:in `/^I perform the (GET|POST) prometheus rest client with:$/'
      /Users/qitang/go/src/github.com/openshift/verification-tests/features/step_definitions/transform.rb:33:in `call'
      /Users/qitang/go/src/github.com/openshift/verification-tests/features/step_definitions/transform.rb:33:in `block in singleton class'
      /Users/qitang/go/src/github.com/openshift/verification-tests/features/step_definitions/meta_steps.rb:48:in `block (2 levels) in <top (required)>'
      /Users/qitang/go/src/github.com/openshift/verification-tests/lib/base_helper.rb:160:in `wait_for'
      /Users/qitang/go/src/github.com/openshift/verification-tests/features/step_definitions/meta_steps.rb:43:in `/^I wait(?: up to ([0-9]+|<%=.+?%>) seconds)? for the steps to pass:$/'
      features/logging/logging_acceptance.feature:118:in `I wait up to 360 seconds for the steps to pass:'
```

### CODE REVIEW

**Comment by QiaolingTang** [comment]
Log: https://url.corp.redhat.com/799b52d

**Comment by QiaolingTang** [comment]
Logs:
4.10: https://url.corp.redhat.com/e550d71
4.11: https://url.corp.redhat.com/fb7a2fd

/hold cancel

**Review by pruan-rht — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
