### PR TITLE
remove oc debug default image for 4.5

### PR DESCRIPTION
**Pull request by rbbratta**
use the  multus cluster image logic so we don't have to access quay.io

see #983

### CODE REVIEW

**Comment by rbbratta** [comment]
http://pastebin.test.redhat.com/869885

**Comment by akostadinov** [comment]
@rbbratta , I see your comment in #983 - `tools:latest being present in openshift namespace`. Can we instead require whoever installs cluster to create that image stream? Or we do it if it doesn't exist? wdyt?

/lgtm

**Comment by rbbratta** [comment]
> @rbbratta , I see your comment in #983 - `tools:latest being present in openshift namespace`. Can we instead require whoever installs cluster to create that image stream? Or we do it if it doesn't exist? wdyt?

I tried, but there is an operator somewhere that resets the imagestreamtag.  

I'll keep investigating, but we probably can't fight the operator.

`oc tag  -n openshift $(oc get pods -n openshift-multus -l app=multus -o jsonpath='{.items[0].spec.containers[?(@.name=="kube-multus")].image}') tools:latest`

**Pull request merged**
