### PR TITLE
add wait time for pod

### PR DESCRIPTION
**Pull request by zhouying7780**
@kasturinarra Please help review , thanks .

### CODE REVIEW

**Comment by kasturinarra** [comment]
@zhouying7780 instead of "Given I wait for steps to pass", can we have some defined value like "Given i wait up to 120 seconds for the steps to pass" or something like that ? thanks !!

**Comment by zhouying7780** [comment]
@kasturinarra  the default time for "Given I wait for steps to pass" is 60s , I think is enough .

**Comment by kasturinarra** [comment]
> @kasturinarra the default time for "Given I wait for steps to pass" is 60s , I think is enough .

okay

**Comment by kasturinarra** [comment]
@liangxia could you please help review and approve ? thanks !!

**Pull request merged**
