### PR TITLE
Add debug steps for SCTP

### PR DESCRIPTION
**Pull request by weliang1**
Sorry, the debug steps not really in the merged https://github.com/openshift/verification-tests/pull/1695.

Create this new PR to add debug steps. This is debug script which is features/test/sctp.feature, the real fixing PR will be copied to features/networking/sctp.feature

@pruan-rht @liangxia
Because this the debug script, I do not think it is needed to be reviewed from team peers.
Please help to merge, the debug information will be useful for a real fixing PR.

### CODE REVIEW

**Comment by pruan-rht** [comment]
@weliang1 instead of merging this, can't you just run it off your debug-branch instead?  I would prefer not to merge debug codes into the master branch.  WDYT?

**Comment by weliang1** [comment]
> @weliang1 instead of merging this, can't you just run it off your debug-branch instead? I would prefer not to merge debug codes into the master branch. WDYT?

@pruan-rht The SCTP automation testing always passed locally but keep failing in our daily CI jobs, I need collect more debug information when the scripts running in CI jobs. Will our daily CI jobs run any scripts from debug-branch? Please advise! Thanks!

**Comment by weliang1** [comment]
> Sorry, the debug steps not really in the merged #1695.
> 
> Create this new PR to add debug steps. This is debug script which is features/test/sctp.feature, the real fixing PR will be copied to features/networking/sctp.feature
> 
> @pruan-rht @liangxia
> Because this the debug script, I do not think it is needed to be reviewed from team peers.
> Please help to merge, the debug information will be useful for a real fixing PR.

@akostadinov Do you have any suggestion about where I should put my debugging script? Eventually real fix will be merger to networking/sctp.feature and test/sctp.feature will be deleted.

**Comment by weliang1** [comment]
> > Sorry, the debug steps not really in the merged #1695.
> > Create this new PR to add debug steps. This is debug script which is features/test/sctp.feature, the real fixing PR will be copied to features/networking/sctp.feature
> > @pruan-rht @liangxia
> > Because this the debug script, I do not think it is needed to be reviewed from team peers.
> > Please help to merge, the debug information will be useful for a real fixing PR.
> 
> @akostadinov Do you have any suggestion about where I should put my debugging script? Eventually real fix will be merger to networking/sctp.feature and test/sctp.feature will be deleted.

Hi Guys, 
https://issues.redhat.com/browse/OCPQE-2834 is still open, this update script may help to get more information to analysis what case the case failed.

Could you guys please let me know where I should merge my script? networking/sctp.feature or test/sctp.feature? Thanks!

CC @zhaozhanqi

**Comment by zhaozhanqi** [comment]
@weliang1 How about only add the debug steps to one case of them for debugging? since `describe` and get nodes will print many logs.

**Comment by akostadinov** [comment]
/lgtm

it's fine to add some such steps where reproducing is hard. Lets in the future merge such PRs quicker.
Just make sure to have proper comments so that later we know which steps to remove. Also maybe add date in the comment. No need to keep debug steps after one year for example.

**Pull request merged**
