### PR TITLE
fix Chrome unknown arguments error

### PR DESCRIPTION
**Pull request by yapei**
Try to fix the unknown arguments error for Chrome

jenkins log on private cluster(with proxy configured)  https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/247866/console 
jenkins log on normal cluster(no proxy) https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/247757/consoleFull

### CODE REVIEW

**Comment by yapei** [comment]
@yanpzhan  @XiyunZhao  @liangxia  @jhou1 Could you help review? Thanks a lot!

**Review by XiyunZhao — APPROVED** [review]

**Comment by jhou1** [comment]
I have also tested with https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/248038/console
/lgtm

**Comment by liangxia** [comment]
/approve

Let's get it merged and watch the CI results.

**Pull request merged**
