### PR TITLE
Add network related tags

### PR DESCRIPTION
**Pull request by liangxia**
/cc @zhaozhanqi @jhou1 @JianLi-RH @dis016 @pruan-rht

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
see still only `network-ovnkubernetes`?

**Comment by liangxia** [comment]
> see still only `network-ovnkubernetes`?

The PR contains tags for `@network-ovnkubernetes` and `@network-multitenant`. E.g, https://github.com/openshift/verification-tests/pull/2765/files#diff-5988860cf440c001e7daa1191c9720d193dc8c66d27333c296a37c135565c67a

We can not render new tags due to Polarion/polarshift outage, will do that in a follow up PR once they are back.

**Comment by zhaozhanqi** [comment]
ah, got it, thanks your reply. @liangxia

**Pull request merged**
